/* md5: 22a4ec8ccfab07100c81350fefd57c6c */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：getEnabledAutoSacle
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1004&itf=6011
 */

import {IsNotEmpty, IsString, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class GetApisAutoscalerV1ServiceAcknowledgementStatusReqDto {
  @IsNotEmpty()
  @IsString()
  'project': string

  @IsNotEmpty()
  @IsString()
  'module': string
}
export class GetApisAutoscalerV1ServiceAcknowledgementStatusResDto {
  @IsNotEmpty()
  @IsNumber()
  'error_code': number

  @IsNotEmpty()
  @IsString()
  'error_message': string

  @IsNotEmpty()
  @IsNumber()
  'toggle_state': number
}
