/* md5: a4acc04ea6c978f9e5624e8782d784b3 */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：Get commits
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1024&itf=6141
 */

import {IsOptional, IsString, IsNotEmpty, IsNumber, ValidateNested, IsArray, IsBoolean} from 'class-validator'
import {Type} from 'class-transformer'
import {ItemEmpty} from '.'

export class Item113839 {
  @IsNotEmpty()
  @IsString()
  'comment': string

  @IsNotEmpty()
  @IsString()
  'created_by': string

  @IsNotEmpty()
  @IsNumber()
  'created_time': number

  @IsNotEmpty()
  @IsString()
  'data': string

  @IsNotEmpty()
  @IsString()
  'env': string

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => ItemEmpty)
  'extra_data': ItemEmpty

  @IsNotEmpty()
  @IsNumber()
  'id': number

  @IsNotEmpty()
  @IsString()
  'project': string

  @IsNotEmpty()
  @IsNumber()
  'service_id': number

  @IsNotEmpty()
  @IsString()
  'service_meta_type': string
}

export class GetApisCmdbV1DepconfCommitGetInfoReqDto {
  /**
    Project module name (smm-api). Specify this or service_id
  */
  @IsOptional()
  @IsString()
  'project'?: string

  /**
    CMDB Service ID. Specify this or project
  */
  @IsOptional()
  @IsString()
  'service_id'?: string

  /**
    environment
  */
  @IsNotEmpty()
  @IsString()
  'env': string

  /**
    Commit ID
  */
  @IsOptional()
  @IsString()
  'commit_id'?: string

  /**
    Next page to retrieve (default: 1)
  */
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  'page'?: number

  /**
    How many records to return (default: 50)
  */
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  'limit'?: number
}
export class GetApisCmdbV1DepconfCommitGetInfoResDto {
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item113839)
  @IsArray()
  'commits': Item113839[]

  /**
    请求业务结果
  */
  @IsNotEmpty()
  @IsBoolean()
  'success': boolean

  @IsNotEmpty()
  @IsNumber()
  'total_count': number
}
