/* md5: 12258bbacf022e5e51943c2b334beefd */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：Get latest few commits in an environment
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1024&itf=6142
 */

import {IsOptional, IsString, IsNumber, ValidateNested, IsArray, IsNotEmpty, IsBoolean} from 'class-validator'
import {Type} from 'class-transformer'
import {ItemEmpty} from '.'

export class Item113856 {
  @IsOptional()
  @IsString()
  'comment'?: string

  @IsOptional()
  @IsString()
  'created_by'?: string

  @IsOptional()
  @IsNumber()
  'created_time'?: number

  @IsOptional()
  @IsString()
  'data'?: string

  @IsOptional()
  @IsString()
  'env'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => ItemEmpty)
  'extra_data'?: ItemEmpty

  @IsOptional()
  @IsNumber()
  'id'?: number

  @IsOptional()
  @IsString()
  'project'?: string

  @IsOptional()
  @IsNumber()
  'service_id'?: number

  @IsOptional()
  @IsString()
  'service_meta_type'?: string
}

export class GetApisCmdbV1DepconfCommitGetLatestChangesReqDto {
  /**
    Project module name (smm-api). Specify this or service_id
  */
  @IsOptional()
  @IsString()
  'project'?: string

  /**
    CMDB Service ID. Specify this or project
  */
  @IsOptional()
  @IsString()
  'service_id'?: string

  /**
    Environment to take from, default to live
  */
  @IsOptional()
  @IsString()
  'env'?: string

  /**
    Retrieve last n commits, defaults to 2
  */
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  'last_n'?: number
}
export class GetApisCmdbV1DepconfCommitGetLatestChangesResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item113856)
  @IsArray()
  'commits'?: Item113856[]

  /**
    请求业务结果
  */
  @IsNotEmpty()
  @IsBoolean()
  'success': boolean

  @IsOptional()
  @IsNumber()
  'total_count'?: number
}
