/* md5: 7dfd2230c73ee2f638d44ec04029b2cb */
/* Rap repository id: 225 */
/* Rapper version: 2.1.10 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：示例接口
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1003&itf=6008
 */

import {IsOptional, IsString, IsNumber, IsBoolean, ValidateNested, IsArray} from 'class-validator'
import {Type} from 'class-transformer'

export class Item108273 {
  /**
    数组元素示例
  */
  @IsOptional()
  @IsString()
  'bar': string

  /**
    数组元素示例
  */
  @IsOptional()
  @IsNumber()
  'foo': number
}

export class GetExample1653979893461ReqDto {
  /**
    请求属性示例
  */
  @IsOptional()
  @IsString()
  'foo': string
}
export class GetExample1653979893461ResDto {
  /**
    字符串属性示例
  */
  @IsOptional()
  @IsString()
  'string': string

  /**
    数字属性示例
  */
  @IsOptional()
  @IsNumber()
  'number': number

  /**
    布尔属性示例
  */
  @IsOptional()
  @IsBoolean()
  'boolean': boolean

  /**
    正则属性示例
  */
  @IsOptional()
  @IsString()
  'regexp': string

  /**
    函数属性示例
  */
  @IsOptional()
  @IsString()
  'function': string

  /**
    数组属性示例
  */
  @IsOptional()
  @ValidateNested()
  @Type(() => Item108273)
  @IsArray()
  'array': Item108273[]

  /**
    自定义数组元素示例
  */
  @IsOptional()
  @IsArray()
  'items': any[]

  /**
    对象属性示例
  */
  @IsOptional()
  @ValidateNested()
  @Type(() => Item108273)
  'object': Item108273

  /**
    占位符示例
  */
  @IsOptional()
  @IsString()
  'placeholder': string
}
