/* md5: ba7b138bf463d1e7db47c51a6569adfb */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：get envs
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1189&itf=7313
 */

import {ValidateNested, IsArray, IsNotEmpty, IsString, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class Item141937 {
  @IsNotEmpty()
  @IsString()
  'alias_name': string

  @IsNotEmpty()
  @IsNumber()
  'enum_value': number

  @IsNotEmpty()
  @IsString()
  'name': string
}

export class GetApisEnvsV2GetEnvsReqDto {}
export class GetApisEnvsV2GetEnvsResDto {
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item141937)
  @IsArray()
  'result': Item141937[]
}
