/* md5: 63ea7aad979f23dcbdd3e6496c12ae42 */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：List all bound services
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1023&itf=6137
 */

import {IsOptional, IsString, IsNumber, ValidateNested, IsArray, IsNotEmpty, IsBoolean} from 'class-validator'
import {Type} from 'class-transformer'

export class Item113810 {
  @IsOptional()
  @IsNumber()
  'created_at'?: number

  @IsOptional()
  @IsNumber()
  'deleted_at'?: number

  @IsOptional()
  @IsString()
  'project'?: string

  @IsOptional()
  @IsNumber()
  'service_id'?: number

  @IsOptional()
  @IsString()
  'service_name'?: string
}

export class GetV1DepconfBindingListReqDto {
  /**
    project module name for exact search
  */
  @IsOptional()
  @IsString()
  'project'?: string

  /**
    cmdb service id
  */
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  'service_id'?: number

  /**
    Returns only disabled records when true
  */
  @IsOptional()
  @IsString()
  'disabled'?: string
}
export class GetV1DepconfBindingListResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item113810)
  @IsArray()
  'projects'?: Item113810[]

  /**
    请求业务结果
  */
  @IsNotEmpty()
  @IsBoolean()
  'success': boolean
}
