/* md5: 9954529707632b13137c62e504594884 */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：Get config cids
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6148
 */

import {IsOptional, IsString, IsNotEmpty, IsArray, IsBoolean} from 'class-validator'

export class GetV1DepconfConfigGetCidsReqDto {
  /**
    Project module name (smm-api). Specify this or service_id
  */
  @IsOptional()
  @IsString()
  'project'?: string

  /**
    CMDB Service ID. Specify this or project
  */
  @IsOptional()
  @IsString()
  'service_id'?: string

  /**
    environment
  */
  @IsNotEmpty()
  @IsString()
  'env': string
}
export class GetV1DepconfConfigGetCidsResDto {
  @IsNotEmpty()
  @IsString({each: true})
  @IsArray()
  'cids': string[]

  /**
    请求业务结果
  */
  @IsNotEmpty()
  @IsBoolean()
  'success': boolean
}
