/* md5: 225eb1a6dd24c27a1ee6a2ca490ee6d3 */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：Get generated service config
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6149
 */

import {IsOptional, IsString, IsNotEmpty, ValidateNested, IsArray, IsBoolean, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'
import {ItemEmpty} from '.'

export class Item114020 {
  @IsOptional()
  @IsString()
  'comment'?: string

  @IsOptional()
  @IsNumber()
  'commit_id'?: number

  @IsOptional()
  @IsString()
  'created_by'?: string

  @IsOptional()
  @IsNumber()
  'created_ts'?: number

  @IsOptional()
  @IsString()
  'data'?: string

  @IsOptional()
  @IsNumber()
  'deleted_at'?: number

  @IsOptional()
  @IsString()
  'env'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => ItemEmpty)
  'extra_data'?: ItemEmpty

  @IsOptional()
  @IsNumber()
  'id'?: number

  @IsOptional()
  @IsString()
  'modified_by'?: string

  @IsOptional()
  @IsNumber()
  'modified_ts'?: number

  @IsOptional()
  @IsString()
  'project'?: string

  @IsOptional()
  @IsNumber()
  'service_id'?: number

  @IsOptional()
  @IsString()
  'service_meta_type'?: string
}

export class GetV1DepconfConfigGetGeneratedReqDto {
  /**
    Project module name (smm-api). Specify this or service_id
  */
  @IsOptional()
  @IsString()
  'project'?: string

  /**
    CMDB Service ID. Specify this or project
  */
  @IsOptional()
  @IsString()
  'service_id'?: string

  /**
    environment
  */
  @IsNotEmpty()
  @IsString()
  'env': string
}
export class GetV1DepconfConfigGetGeneratedResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item114020)
  @IsArray()
  'configurations'?: Item114020[]

  /**
    请求业务结果
  */
  @IsNotEmpty()
  @IsBoolean()
  'success': boolean

  @IsOptional()
  @IsNumber()
  'total_count'?: number
}
