/* md5: 4c5707eb78c983e6c4ad9628d6bf1d23 */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：get unbounded sdus
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1172&itf=7276
 */

import {IsOptional, IsString, ValidateNested, IsArray, IsNotEmpty, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'
import {ItemEmpty} from '.'

export class Item141454 {
  @IsNotEmpty()
  @IsString()
  'cid': string

  @IsNotEmpty()
  @IsNumber()
  'created_at': number

  @IsNotEmpty()
  @IsString()
  'deployment_link': string

  @IsNotEmpty()
  @IsString()
  'env': string

  @IsNotEmpty()
  @IsArray()
  'idcs': any[]

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => ItemEmpty)
  'label': ItemEmpty

  @IsNotEmpty()
  @IsString()
  'resource_type': string

  @IsNotEmpty()
  @IsString()
  'sdu': string

  @IsNotEmpty()
  @IsNumber()
  'updated_at': number

  @IsNotEmpty()
  @IsString()
  'version': string
}

export class GetApisCmdbV2ServiceGetUnboundedSdusReqDto {
  /**
    APP/CONTAINER/PHYSICAL/STATIC
默认APP
  */
  @IsOptional()
  @IsString()
  'resource_type'?: string
}
export class GetApisCmdbV2ServiceGetUnboundedSdusResDto {
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item141454)
  @IsArray()
  'sdus': Item141454[]

  @IsNotEmpty()
  @IsNumber()
  'total_size': number
}
