/* md5: a143d07c88ea902c9b60fc76cc917942 */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：Get all configs
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6147
 */

import {IsOptional, IsString, IsNumber, ValidateNested, IsArray, IsNotEmpty, IsBoolean} from 'class-validator'
import {Type} from 'class-transformer'
import {ItemEmpty} from '.'

export class Item114006 {
  @IsOptional()
  @IsBoolean()
  'has_next'?: boolean

  @IsOptional()
  @IsNumber()
  'next_id'?: number
}

export class Item113992 {
  @IsOptional()
  @IsString()
  'comment'?: string

  @IsOptional()
  @IsNumber()
  'commit_id'?: number

  @IsOptional()
  @IsString()
  'created_by'?: string

  @IsOptional()
  @IsNumber()
  'created_ts'?: number

  @IsOptional()
  @IsString()
  'data'?: string

  @IsOptional()
  @IsNumber()
  'deleted_at'?: number

  @IsOptional()
  @IsString()
  'env'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => ItemEmpty)
  'extra_data'?: ItemEmpty

  @IsOptional()
  @IsNumber()
  'id'?: number

  @IsOptional()
  @IsString()
  'modified_by'?: string

  @IsOptional()
  @IsNumber()
  'modified_ts'?: number

  @IsOptional()
  @IsString()
  'project'?: string

  @IsOptional()
  @IsNumber()
  'service_id'?: number

  @IsOptional()
  @IsString()
  'service_meta_type'?: string
}

export class GetV1DepconfConfigGetAllReqDto {
  /**
    Environment to retrieve from
  */
  @IsOptional()
  @IsString()
  'env'?: string

  /**
    Next config ID to retrieve from (default: 0)
  */
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  'next_id'?: number

  /**
    How many records to return (default: 50)
  */
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  'limit'?: number
}
export class GetV1DepconfConfigGetAllResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item113992)
  @IsArray()
  'configurations'?: Item113992[]

  @IsOptional()
  @ValidateNested()
  @Type(() => Item114006)
  'meta'?: Item114006

  /**
    请求业务结果
  */
  @IsNotEmpty()
  @IsBoolean()
  'success': boolean

  @IsOptional()
  @IsNumber()
  'total_count'?: number
}
