/* md5: dd16a5b83bac90ff88d80054748b90c9 */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：List deployment zones this config is apart of
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6152
 */

import {IsOptional, IsString, IsNotEmpty, IsBoolean, ValidateNested, IsArray, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class Item114066 {
  @IsOptional()
  @IsArray()
  'envs'?: any[]

  @IsOptional()
  @IsString()
  'full_name'?: string

  @IsOptional()
  @IsNumber()
  'id'?: number

  @IsOptional()
  @IsString()
  'name'?: string

  @IsOptional()
  @IsString()
  'namespace'?: string

  @IsOptional()
  @IsString()
  'zone_type'?: string

  @IsOptional()
  @IsNumber()
  'zone_val'?: number
}

export class GetV1DepconfConfigListDeploymentZoneReqDto {
  /**
    Project module name (smm-api). Specify this or service_id
  */
  @IsOptional()
  @IsString()
  'project'?: string

  /**
    CMDB Service ID. Specify this or project
  */
  @IsOptional()
  @IsString()
  'service_id'?: string
}
export class GetV1DepconfConfigListDeploymentZoneResDto {
  /**
    请求业务结果
  */
  @IsNotEmpty()
  @IsBoolean()
  'success': boolean

  @IsOptional()
  @ValidateNested()
  @Type(() => Item114066)
  @IsArray()
  'zones'?: Item114066[]
}
