/* md5: 8252820a46d95746195db3d6d4067b87 */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：test
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1172&itf=8887
 */

export class GetTestReqDto {}
export class GetTestResDto {}
