/* md5: b79bcbef715137fb7964968ea6d765fa */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

export class ItemEmpty {}

export {
  PostV1DepconfBindingBindServiceReqDto,
  PostV1DepconfBindingBindServiceResDto,
} from './post-v1-depconf-binding-bind_service.dto'
export {GetV1DepconfBindingListReqDto, GetV1DepconfBindingListResDto} from './get-v1-depconf-binding-list.dto'
export {
  PostV1DepconfBindingUnbindServiceReqDto,
  PostV1DepconfBindingUnbindServiceResDto,
} from './post-v1-depconf-binding-unbind_service.dto'
export {
  PostApisCmdbV1DepconfCommitCopyToReqDto,
  PostApisCmdbV1DepconfCommitCopyToResDto,
} from './post-apis-cmdb-v1-depconf-commit-copy_to.dto'
export {
  PostApisCmdbV1DepconfCommitCreateReqDto,
  PostApisCmdbV1DepconfCommitCreateResDto,
} from './post-apis-cmdb-v1-depconf-commit-create.dto'
export {
  GetApisCmdbV1DepconfCommitGetInfoReqDto,
  GetApisCmdbV1DepconfCommitGetInfoResDto,
} from './get-apis-cmdb-v1-depconf-commit-get_info.dto'
export {
  GetApisCmdbV1DepconfCommitGetLatestChangesReqDto,
  GetApisCmdbV1DepconfCommitGetLatestChangesResDto,
} from './get-apis-cmdb-v1-depconf-commit-get_latest_changes.dto'
export {
  PostV1DepconfConfigAddDeploymentZoneReqDto,
  PostV1DepconfConfigAddDeploymentZoneResDto,
} from './post-v1-depconf-config-add_deployment_zone.dto'
export {
  PostV1DepconfConfigBulkGetFieldReqDto,
  PostV1DepconfConfigBulkGetFieldResDto,
} from './post-v1-depconf-config-bulk_get_field.dto'
export {PostV1DepconfConfigDeleteReqDto, PostV1DepconfConfigDeleteResDto} from './post-v1-depconf-config-delete.dto'
export {
  PostV1DepconfConfigDeleteDeploymentZoneReqDto,
  PostV1DepconfConfigDeleteDeploymentZoneResDto,
} from './post-v1-depconf-config-delete_deployment_zone.dto'
export {GetV1DepconfConfigGetAllReqDto, GetV1DepconfConfigGetAllResDto} from './get-v1-depconf-config-get_all.dto'
export {GetV1DepconfConfigGetCidsReqDto, GetV1DepconfConfigGetCidsResDto} from './get-v1-depconf-config-get_cids.dto'
export {
  GetV1DepconfConfigGetGeneratedReqDto,
  GetV1DepconfConfigGetGeneratedResDto,
} from './get-v1-depconf-config-get_generated.dto'
export {GetV1DepconfConfigGetInfoReqDto, GetV1DepconfConfigGetInfoResDto} from './get-v1-depconf-config-get_info.dto'
export {
  GetV1DepconfConfigGetMinimumInstanceReqDto,
  GetV1DepconfConfigGetMinimumInstanceResDto,
} from './get-v1-depconf-config-get_minimum_instance.dto'
export {
  GetV1DepconfConfigListDeploymentZoneReqDto,
  GetV1DepconfConfigListDeploymentZoneResDto,
} from './get-v1-depconf-config-list_deployment_zone.dto'
export {
  PostV1DepconfConfigUpdateIdcReqDto,
  PostV1DepconfConfigUpdateIdcResDto,
} from './post-v1-depconf-config-update_idc.dto'
export {
  PostV1DepconfConfigUpdateInstanceReqDto,
  PostV1DepconfConfigUpdateInstanceResDto,
} from './post-v1-depconf-config-update_instance.dto'
export {
  PostV1DepconfConfigUpdateInstancesReqDto,
  PostV1DepconfConfigUpdateInstancesResDto,
} from './post-v1-depconf-config-update_instances.dto'
export {
  PostV1DepconfConfigUpdateOrchestratorReqDto,
  PostV1DepconfConfigUpdateOrchestratorResDto,
} from './post-v1-depconf-config-update_orchestrator.dto'
export {
  PostV1DepconfConfigUpdateOvercommitsReqDto,
  PostV1DepconfConfigUpdateOvercommitsResDto,
} from './post-v1-depconf-config-update_overcommits.dto'
export {
  PostV1DepconfConfigUpdateResourceReqDto,
  PostV1DepconfConfigUpdateResourceResDto,
} from './post-v1-depconf-config-update_resource.dto'
export {
  GetApisAutoscalerV1ServiceAcknowledgementStatusReqDto,
  GetApisAutoscalerV1ServiceAcknowledgementStatusResDto,
} from './get-apis-autoscaler-v1-service-acknowledgement_status.dto'
export {
  GetApisCmdbV2ServiceGetUnboundedSdusReqDto,
  GetApisCmdbV2ServiceGetUnboundedSdusResDto,
} from './get-apis-cmdb-v2-service-get_unbounded_sdus.dto'
export {
  PostApisCmdbV2ServiceBindSduReqDto,
  PostApisCmdbV2ServiceBindSduResDto,
} from './post-apis-cmdb-v2-service-bind_sdu.dto'
export {
  PostApisCmdbV2ServiceUnbindSduReqDto,
  PostApisCmdbV2ServiceUnbindSduResDto,
} from './post-apis-cmdb-v2-service-unbind_sdu.dto'
export {GetTestReqDto, GetTestResDto} from './get-test.dto'
export {GetApisEnvsV2GetEnvsReqDto, GetApisEnvsV2GetEnvsResDto} from './get-apis-envs-v2-get_envs.dto'
export {GetApisEnvsV2GetCidsReqDto, GetApisEnvsV2GetCidsResDto} from './get-apis-envs-v2-get_cids.dto'
