/* md5: 69dff77c88a76deffd48d34f52626c4c */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：Copy a commit  to other environment
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1024&itf=6139
 */

import {IsOptional, IsString, IsNumber, IsArray} from 'class-validator'
import {Type} from 'class-transformer'

export class PostApisCmdbV1DepconfCommitCopyToReqDto {
  @IsOptional()
  @IsString()
  'comment'?: string

  @IsOptional()
  @IsNumber()
  'from_commit_id'?: number

  @IsOptional()
  @IsString()
  'project'?: string

  @IsOptional()
  @IsNumber()
  'service_id'?: number

  @IsOptional()
  @IsString()
  'service_meta_type'?: string

  @IsOptional()
  @IsArray()
  'targets'?: any[]
}
export class PostApisCmdbV1DepconfCommitCopyToResDto {}
