/* md5: ed24c9eae90a6db45ad124a71fe29ef5 */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：Create a commit
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1024&itf=6140
 */

import {IsNotEmpty, IsString, IsOptional, ValidateNested, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'
import {ItemEmpty} from '.'

export class PostApisCmdbV1DepconfCommitCreateReqDto {
  @IsNotEmpty()
  @IsString()
  'comment': string

  @IsNotEmpty()
  @IsString()
  'data': string

  @IsOptional()
  @IsString()
  'email'?: string

  @IsNotEmpty()
  @IsString()
  'env': string

  @IsOptional()
  @ValidateNested()
  @Type(() => ItemEmpty)
  'extra_data'?: ItemEmpty

  @IsOptional()
  @IsString()
  'project'?: string

  @IsNotEmpty()
  @IsNumber()
  'service_id': number

  @IsOptional()
  @IsString()
  'service_meta_type'?: string
}
export class PostApisCmdbV1DepconfCommitCreateResDto {}
