/* md5: aa605e00c10a6f85695a6470de24f324 */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：Retrieves a field from multiple services
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6144
 */

import {IsOptional, IsString, IsArray, IsNumber, ValidateNested, IsBoolean} from 'class-validator'
import {Type} from 'class-transformer'
import {ItemEmpty} from '.'

export class Item113974 {
  @IsOptional()
  @IsString()
  'key'?: string

  @IsOptional()
  @IsString()
  'operator'?: string

  @IsOptional()
  @IsString()
  'value'?: string

  @IsOptional()
  @IsArray()
  'values'?: any[]
}

export class Item113968 {
  @IsOptional()
  @IsNumber()
  'max_instances'?: number

  @IsOptional()
  @ValidateNested()
  @Type(() => Item113974)
  @IsArray()
  'selectors'?: Item113974[]

  /**
    Only `agent_id` is supported so far.
  */
  @IsOptional()
  @IsString()
  'unique_key'?: string
}

export class Item113953 {
  @IsOptional()
  @IsString()
  'name'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item113968)
  'parameters'?: Item113968
}

export class Item113951 {
  @IsOptional()
  @IsArray()
  'canary_stages'?: any[]

  @IsOptional()
  @IsBoolean()
  'disable_restart'?: boolean

  @IsOptional()
  @IsBoolean()
  'enable_canary_replacement'?: boolean

  @IsOptional()
  @IsBoolean()
  'in_place'?: boolean

  @IsOptional()
  @IsNumber()
  'instances_per_agent'?: number

  @IsOptional()
  @IsString()
  'max_surge'?: string

  @IsOptional()
  @IsString()
  'max_unavailable'?: string

  @IsOptional()
  @IsBoolean()
  'reserve_resources'?: boolean

  @IsOptional()
  @IsNumber()
  'step_down'?: number

  @IsOptional()
  @IsBoolean()
  'strict_in_place'?: boolean

  @IsOptional()
  @IsNumber()
  'threshold'?: number
}

export class Item113950 {
  @IsOptional()
  @IsNumber()
  'cpu'?: number

  @IsOptional()
  @IsNumber()
  'disk'?: number

  @IsOptional()
  @IsNumber()
  'gpu'?: number

  @IsOptional()
  @IsNumber()
  'mem'?: number
}

export class Item113949 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item113953)
  @IsArray()
  'assignment_policies'?: Item113953[]

  @IsOptional()
  @IsString()
  'orchestrator'?: string
}

export class Item113944 {
  @IsOptional()
  @IsString()
  'name'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item113951)
  'parameters'?: Item113951
}

export class Item113937 {
  @IsOptional()
  @ValidateNested()
  @Type(() => ItemEmpty)
  'annotations'?: ItemEmpty

  @IsOptional()
  @IsNumber()
  'canary_instances'?: number

  @IsOptional()
  @IsNumber()
  'canary_percent'?: number

  @IsOptional()
  @IsNumber()
  'instances'?: number

  @IsOptional()
  @IsNumber()
  'minimum_instances'?: number

  @IsOptional()
  @ValidateNested()
  @Type(() => Item113950)
  'resources'?: Item113950

  @IsOptional()
  @ValidateNested()
  @Type(() => Item113949)
  'scheduler'?: Item113949

  @IsOptional()
  @ValidateNested()
  @Type(() => Item113944)
  'strategy'?: Item113944
}

export class Item113936 {
  @IsOptional()
  @IsString()
  'az'?: string

  @IsOptional()
  @IsString()
  'cid'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item113937)
  'data'?: Item113937

  @IsOptional()
  @IsString()
  'env'?: string

  @IsOptional()
  @IsString()
  'project_module'?: string

  @IsOptional()
  @IsNumber()
  'service_id'?: number
}

export class PostV1DepconfConfigBulkGetFieldReqDto {
  @IsOptional()
  @IsString()
  'env'?: string

  @IsOptional()
  @IsArray()
  'fields'?: any[]

  @IsOptional()
  @IsNumber()
  'limit'?: number

  @IsOptional()
  @IsNumber()
  'next_id'?: number

  @IsOptional()
  @IsArray()
  'project_modules'?: any[]

  @IsOptional()
  @IsArray()
  'service_ids'?: any[]

  @IsOptional()
  @IsString()
  'service_meta_type'?: string
}
export class PostV1DepconfConfigBulkGetFieldResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item113936)
  @IsArray()
  'configs'?: Item113936[]
}
