/* md5: 05aa8281c990b5eff832133bfa3ebaa6 */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：Update idcs of a project
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6153
 */

import {IsNotEmpty, IsString, IsOptional, IsArray, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class PostV1DepconfConfigUpdateIdcReqDto {
  @IsNotEmpty()
  @IsString()
  'cid': string

  @IsOptional()
  @IsString()
  'comment'?: string

  @IsNotEmpty()
  @IsString()
  'env': string

  @IsNotEmpty()
  @IsArray()
  'idcs': any[]

  @IsOptional()
  @IsString()
  'operation'?: string

  @IsOptional()
  @IsString()
  'project'?: string

  @IsOptional()
  @IsNumber()
  'service_id'?: number

  @IsOptional()
  @IsString()
  'service_meta_type'?: string
}
export class PostV1DepconfConfigUpdateIdcResDto {}
