/* md5: a50651b06b2d72401b7bd231f6d85203 */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：Update instance count for a project
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6154
 */

import {IsNotEmpty, IsString, IsOptional} from 'class-validator'

export class PostV1DepconfConfigUpdateInstanceReqDto {
  /**
    project
  */
  @IsNotEmpty()
  @IsString()
  'project': string

  /**
    env
  */
  @IsNotEmpty()
  @IsString()
  'env': string

  /**
    cid
  */
  @IsNotEmpty()
  @IsString()
  'cid': string

  /**
    idc
  */
  @IsOptional()
  @IsString()
  'idc'?: string

  /**
    count
  */
  @IsNotEmpty()
  @IsString()
  'count': string

  /**
    comment
  */
  @IsOptional()
  @IsString()
  'comment'?: string
}
export class PostV1DepconfConfigUpdateInstanceResDto {}
