/* md5: 9e2ac3377d65aca21276d57f5e9335f1 */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：Deletes all configs for this service
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6145
 */

import {IsOptional, IsString, IsNumber, IsNotEmpty, IsBoolean} from 'class-validator'
import {Type} from 'class-transformer'

export class PostV1DepconfConfigDeleteReqDto {
  @IsOptional()
  @IsString()
  'email'?: string

  @IsOptional()
  @IsString()
  'project'?: string

  @IsOptional()
  @IsNumber()
  'service_id'?: number

  @IsOptional()
  @IsString()
  'service_meta_type'?: string
}
export class PostV1DepconfConfigDeleteResDto {
  /**
    请求业务结果
  */
  @IsNotEmpty()
  @IsBoolean()
  'success': boolean
}
