/* md5: 972f8df7cf202185e9c83d917b15ff85 */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：Delete deployment zones from this config
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6146
 */

import {IsNotEmpty, IsString, IsOptional, IsNumber, IsArray, IsBoolean} from 'class-validator'
import {Type} from 'class-transformer'

export class PostV1DepconfConfigDeleteDeploymentZoneReqDto {
  /**
    Deployment zone IDs to delete
  */
  @IsNotEmpty()
  @IsString()
  'dz_type': string

  @IsOptional()
  @IsString()
  'project'?: string

  /**
    CMDB Service ID
  */
  @IsOptional()
  @IsNumber()
  'service_id'?: number

  @IsOptional()
  @IsArray()
  'zone_ids'?: any[]
}
export class PostV1DepconfConfigDeleteDeploymentZoneResDto {
  /**
    请求业务结果
  */
  @IsNotEmpty()
  @IsBoolean()
  'success': boolean
}
