/* md5: 61c4de7114a0ae5860f6c663fa3822b0 */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：Update instances count for a project
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6155
 */

import {IsOptional, IsString, IsNotEmpty, ValidateNested, IsArray, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class Item114092 {
  @IsNotEmpty()
  @IsString()
  'cid': string

  @IsNotEmpty()
  @IsNumber()
  'count': number

  @IsNotEmpty()
  @IsString()
  'idc': string
}

export class PostV1DepconfConfigUpdateInstancesReqDto {
  @IsOptional()
  @IsString()
  'comment'?: string

  @IsOptional()
  @IsString()
  'email'?: string

  @IsNotEmpty()
  @IsString()
  'env': string

  @IsOptional()
  @IsString()
  'project'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item114092)
  @IsArray()
  'requests'?: Item114092[]

  @IsOptional()
  @IsNumber()
  'service_id'?: number

  @IsOptional()
  @IsString()
  'service_meta_type'?: string
}
export class PostV1DepconfConfigUpdateInstancesResDto {}
