/* md5: 512190b2d854fe1f15d3fa66e0f5b829 */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：Update overcommit factors and policy count for a project
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6157
 */

import {IsOptional, IsString, IsNotEmpty, ValidateNested, IsArray, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class Item114110 {
  @IsNotEmpty()
  @IsString()
  'cid': string

  @IsNotEmpty()
  @IsString()
  'idc': string

  @IsNotEmpty()
  @IsNumber()
  'overcommit_factor': number

  @IsNotEmpty()
  @IsString()
  'overcommit_policy': string

  @IsOptional()
  @IsString()
  'usage_class'?: string
}

export class PostV1DepconfConfigUpdateOvercommitsReqDto {
  @IsOptional()
  @IsString()
  'comment'?: string

  @IsOptional()
  @IsString()
  'email'?: string

  @IsNotEmpty()
  @IsString()
  'env': string

  @IsOptional()
  @IsString()
  'project'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item114110)
  @IsArray()
  'requests'?: Item114110[]

  @IsOptional()
  @IsNumber()
  'service_id'?: number

  @IsOptional()
  @IsString()
  'service_meta_type'?: string
}
export class PostV1DepconfConfigUpdateOvercommitsResDto {}
