/* md5: 7f6d4b0bc9c0933df423e18cb02afa1e */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：Add a deployment zone to this config
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6143
 */

import {IsOptional, IsString, IsNumber, ValidateNested, IsArray, IsNotEmpty, IsBoolean} from 'class-validator'
import {Type} from 'class-transformer'

export class Item113923 {
  @IsOptional()
  @IsString()
  'key'?: string

  @IsOptional()
  @IsString()
  'operator'?: string

  @IsOptional()
  @IsString()
  'value'?: string

  @IsOptional()
  @IsArray()
  'values'?: any[]
}

export class Item113920 {
  @IsOptional()
  @IsNumber()
  'max_instances'?: number

  @IsOptional()
  @ValidateNested()
  @Type(() => Item113923)
  @IsArray()
  'selectors'?: Item113923[]

  /**
    Only `agent_id` is supported so far.
  */
  @IsOptional()
  @IsString()
  'unique_key'?: string
}

export class Item113906 {
  @IsOptional()
  @IsString()
  'name'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item113920)
  'parameters'?: Item113920
}

export class Item113900 {
  @IsOptional()
  @IsArray()
  'canary_stages'?: any[]

  @IsOptional()
  @IsBoolean()
  'disable_restart'?: boolean

  @IsOptional()
  @IsBoolean()
  'enable_canary_replacement'?: boolean

  @IsOptional()
  @IsBoolean()
  'in_place'?: boolean

  @IsOptional()
  @IsNumber()
  'instances_per_agent'?: number

  @IsOptional()
  @IsString()
  'max_surge'?: string

  @IsOptional()
  @IsString()
  'max_unavailable'?: string

  @IsOptional()
  @IsBoolean()
  'reserve_resources'?: boolean

  @IsOptional()
  @IsNumber()
  'step_down'?: number

  @IsOptional()
  @IsBoolean()
  'strict_in_place'?: boolean

  @IsOptional()
  @IsNumber()
  'threshold'?: number
}

export class Item113896 {
  @IsOptional()
  @IsString()
  'final'?: string

  @IsOptional()
  @IsArray()
  'stages'?: any[]
}

export class Item113894 {
  @IsOptional()
  @IsString()
  'name'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item113900)
  'parameters'?: Item113900
}

export class Item113890 {
  @IsOptional()
  @IsString()
  'instances'?: string

  @IsOptional()
  @IsString()
  'mode'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item113896)
  'multi_stage'?: Item113896
}

export class Item113889 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item113906)
  @IsArray()
  'assignment_policies'?: Item113906[]
}

export class Item113888 {
  @IsOptional()
  @IsNumber()
  'cpu'?: number

  @IsOptional()
  @IsNumber()
  'disk'?: number

  @IsOptional()
  @IsNumber()
  'gpu'?: number

  @IsOptional()
  @IsNumber()
  'mem'?: number

  @IsOptional()
  @IsBoolean()
  'skip_mem_limit_check'?: boolean
}

export class Item113887 {
  @IsOptional()
  @IsBoolean()
  'enabled'?: boolean
}

export class Item113885 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item113890)
  'canary'?: Item113890

  @IsOptional()
  @IsBoolean()
  'enabled'?: boolean

  @IsOptional()
  @IsNumber()
  'instances'?: number

  @IsOptional()
  @IsNumber()
  'minimum_instances'?: number

  @IsOptional()
  @ValidateNested()
  @Type(() => Item113888)
  'resources'?: Item113888

  @IsOptional()
  @ValidateNested()
  @Type(() => Item113889)
  'scheduler'?: Item113889

  @IsOptional()
  @ValidateNested()
  @Type(() => Item113894)
  'strategy'?: Item113894
}

export class Item113876 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item113885)
  'container'?: Item113885

  @IsOptional()
  @IsString()
  'env'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item113887)
  'static_files'?: Item113887
}

export class Item113875 {
  @IsOptional()
  @IsArray()
  'envs'?: any[]

  @IsOptional()
  @IsString()
  'full_name'?: string

  @IsOptional()
  @IsNumber()
  'id'?: number

  @IsOptional()
  @IsString()
  'name'?: string

  @IsOptional()
  @IsString()
  'namespace'?: string

  @IsOptional()
  @IsString()
  'zone_type'?: string

  @IsOptional()
  @IsNumber()
  'zone_val'?: number
}

export class Item113872 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item113876)
  @IsArray()
  'envs'?: Item113876[]
}

export class Item113871 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item113872)
  'definition'?: Item113872

  @IsOptional()
  @IsString()
  'dz_type'?: string

  @IsOptional()
  @IsNumber()
  'zone_id'?: number
}

export class PostV1DepconfConfigAddDeploymentZoneReqDto {
  /**
    Project is a combination of $project-$module
  */
  @IsOptional()
  @IsString()
  'project'?: string

  /**
    CMDB Service ID
  */
  @IsOptional()
  @IsNumber()
  'service_id'?: number

  @IsOptional()
  @ValidateNested()
  @Type(() => Item113871)
  @IsArray()
  'zones'?: Item113871[]
}
export class PostV1DepconfConfigAddDeploymentZoneResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item113875)
  @IsArray()
  'bound_zones'?: Item113875[]

  /**
    请求业务结果
  */
  @IsNotEmpty()
  @IsBoolean()
  'success': boolean
}
