/* md5: c83cf053b52138d55b2adcf756ec35ef */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：Update orchestrator of a project
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6156
 */

import {IsOptional, IsString, IsArray, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class PostV1DepconfConfigUpdateOrchestratorReqDto {
  @IsOptional()
  @IsString()
  'cid'?: string

  @IsOptional()
  @IsString()
  'email'?: string

  @IsOptional()
  @IsString()
  'env'?: string

  @IsOptional()
  @IsArray()
  'idcs'?: any[]

  @IsOptional()
  @IsString()
  'orchestrator'?: string

  @IsOptional()
  @IsString()
  'project'?: string

  @IsOptional()
  @IsNumber()
  'service_id'?: number

  @IsOptional()
  @IsString()
  'service_meta_type'?: string
}
export class PostV1DepconfConfigUpdateOrchestratorResDto {}
