/* md5: 0e55b9203bd8832668ddacc7d4cbde03 */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

/**
 * Interface name：Update resource project
 * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6158
 */

import {IsOptional, IsString, IsNotEmpty, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class PostV1DepconfConfigUpdateResourceReqDto {
  @IsOptional()
  @IsString()
  'comment'?: string

  @IsNotEmpty()
  @IsNumber()
  'cpu': number

  @IsNotEmpty()
  @IsString()
  'env': string

  @IsNotEmpty()
  @IsNumber()
  'mem': number

  @IsOptional()
  @IsString()
  'project'?: string

  @IsOptional()
  @IsNumber()
  'service_id'?: number

  @IsOptional()
  @IsString()
  'service_meta_type'?: string
}
export class PostV1DepconfConfigUpdateResourceResDto {}
