/* md5: 75415dc8540c6f03386245aa21a2834b */
/* Rap repository id: 247 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=247
 */

/**
 * Interface name：Get Tenants
 * Rap url: https://rap.shopee.io/repository/editor?id=247&mod=1376&itf=8643
 */

import {IsOptional, IsBoolean, ValidateNested, IsArray, IsNotEmpty, IsNumber, IsString} from 'class-validator'
import {Type} from 'class-transformer'

export class Item165563 {
  @IsNotEmpty()
  @IsNumber({}, {each: true})
  @IsArray()
  'team_ids': number[]

  @IsNotEmpty()
  @IsString()
  'user_email': string

  @IsNotEmpty()
  @IsNumber()
  'user_id': number
}

export class Item165560 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item165563)
  @IsArray()
  'engineering_managers'?: Item165563[]

  @IsNotEmpty()
  @IsNumber()
  'tenant_id': number

  @IsNotEmpty()
  @IsString({each: true})
  @IsArray()
  'tenant_name': string[]
}

export class GetApisCmdbV2ServiceTenantGetReqDto {
  @IsOptional()
  @IsBoolean()
  'show_details'?: boolean
}
export class GetApisCmdbV2ServiceTenantGetResDto {
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item165560)
  @IsArray()
  'tenants': Item165560[]

  @IsNotEmpty()
  @IsNumber()
  'business_code': number

  @IsNotEmpty()
  @IsBoolean()
  'success': boolean
}
