/* md5: 963bd1056e4a4f9cfffa08f91fe20dba */
/* Rap repository id: 247 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=247
 */

export {
  GetApisCmdbV2ServiceTenantGetReqDto,
  GetApisCmdbV2ServiceTenantGetResDto,
} from './get-apis-cmdb-v2-service-tenant-get.dto'
