/* md5: 668df611b8593cafdb98da31066b3f01 */
/* Rap repository id: 228 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=228
 */

export const IReqType = {}
