/* md5: f34718fb5fb198208d8341a1a6b7aa56 */
/* Rap repository id: 234 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=234
 */

export {
  PostApisUicV2AuthTokenValidateReqDto,
  PostApisUicV2AuthTokenValidateResDto,
} from './post-apis-uic-v2-auth-token_validate.dto'
