/* md5: 30dcd4a4b70a69124cf14ec10a9e77c3 */
/* Rap repository id: 234 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=234
 */

/**
 * Interface name：validate UIC token
 * Rap url: https://rap.shopee.io/repository/editor?id=234&mod=1196&itf=7347
 */

import {ValidateNested, IsNotEmpty, IsString, IsNumber, IsBoolean} from 'class-validator'
import {Type} from 'class-transformer'

export class Item142881 {
  @IsNotEmpty()
  @IsString()
  'create_time': string

  @IsNotEmpty()
  @IsString()
  'description': string

  @IsNotEmpty()
  @IsString()
  'email': string

  @IsNotEmpty()
  @IsString()
  'family_name': string

  @IsNotEmpty()
  @IsString()
  'full_name': string

  @IsNotEmpty()
  @IsString()
  'given_name': string

  @IsNotEmpty()
  @IsBoolean()
  'is_bot': boolean

  @IsNotEmpty()
  @IsBoolean()
  'limited': boolean

  @IsNotEmpty()
  @IsString()
  'locale': string

  @IsNotEmpty()
  @IsString()
  'name': string

  @IsNotEmpty()
  @IsString()
  'picture': string

  @IsNotEmpty()
  @IsString()
  'sub': string

  @IsNotEmpty()
  @IsString()
  'update_time': string

  @IsNotEmpty()
  @IsString()
  'username': string
}

export class PostApisUicV2AuthTokenValidateReqDto {}
export class PostApisUicV2AuthTokenValidateResDto {
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item142881)
  'user': Item142881

  @IsNotEmpty()
  @IsString()
  'token': string

  @IsNotEmpty()
  @IsNumber()
  'time': number

  @IsNotEmpty()
  @IsNumber()
  'expireAt': number
}
