/* md5: 439abc62192d9f4d05bf6ac071e8553d */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

export const IReqType = {
  'POST/v1/depconf/config/update_instance': {project: 2, env: 2, cid: 2, idc: 2, count: 2, comment: 2},
}
