/* md5: 341ae72ec7dcb9e3626e0b7e3b0c093f */
/* Rap repository id: 225 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=225
 */

import * as commonLib from '@infra/rapper/runtime/commonLib'
import {IReqType} from './extra'

export interface IModels {
  /**
   * Interface name：Binds a cmdb service to a project
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1023&itf=6136
   */
  'POST/v1/depconf/binding/bind_service': {
    Req: {
      project?: string
      service_id?: number
      service_name?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      created_at?: number
      deleted_at?: number
      project?: string
      service_id?: number
      service_name?: string
      /**
       * 请求业务结果
       */
      success: boolean
    }
  }

  /**
   * Interface name：List all bound services
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1023&itf=6137
   */
  'GET/v1/depconf/binding/list': {
    Req: {
      /**
       * project module name for exact search
       */
      project?: string
      /**
       * cmdb service id
       */
      service_id?: number
      /**
       * Returns only disabled records when true
       */
      disabled?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      projects?: {
        created_at?: number
        service_id?: number
        deleted_at?: number
        service_name?: string
        project?: string
      }[]
      /**
       * 请求业务结果
       */
      success: boolean
    }
  }

  /**
   * Interface name：Binds a cmdb service to a project
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1023&itf=6138
   */
  'POST/v1/depconf/binding/unbind_service': {
    Req: {
      service_id?: number
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      /**
       * 请求业务结果
       */
      success: boolean
    }
  }

  /**
   * Interface name：Copy a commit  to other environment
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1024&itf=6139
   */
  'POST/apis/cmdb/v1/depconf/commit/copy_to': {
    Req: {
      comment?: string
      from_commit_id?: number
      project?: string
      service_id?: number
      service_meta_type?: string
      targets?: unknown[]
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {}
  }

  /**
   * Interface name：Create a commit
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1024&itf=6140
   */
  'POST/apis/cmdb/v1/depconf/commit/create': {
    Req: {
      comment: string
      data: string
      email?: string
      env: string
      extra_data?: {}
      project?: string
      service_id: number
      service_meta_type?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {}
  }

  /**
   * Interface name：Get commits
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1024&itf=6141
   */
  'GET/apis/cmdb/v1/depconf/commit/get_info': {
    Req: {
      /**
       * Project module name (smm-api). Specify this or service_id
       */
      project?: string
      /**
       * CMDB Service ID. Specify this or project
       */
      service_id?: string
      /**
       * environment
       */
      env: string
      /**
       * Commit ID
       */
      commit_id?: string
      /**
       * Next page to retrieve (default: 1)
       */
      page?: number
      /**
       * How many records to return (default: 50)
       */
      limit?: number
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      commits: {
        env: string
        comment: string
        created_by: string
        data: string
        extra_data: {}
        created_time: number
        project: string
        id: number
        service_id: number
        service_meta_type: string
      }[]
      /**
       * 请求业务结果
       */
      success: boolean
      total_count: number
    }
  }

  /**
   * Interface name：Get latest few commits in an environment
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1024&itf=6142
   */
  'GET/apis/cmdb/v1/depconf/commit/get_latest_changes': {
    Req: {
      /**
       * Project module name (smm-api). Specify this or service_id
       */
      project?: string
      /**
       * CMDB Service ID. Specify this or project
       */
      service_id?: string
      /**
       * Environment to take from, default to live
       */
      env?: string
      /**
       * Retrieve last n commits, defaults to 2
       */
      last_n?: number
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      commits?: {
        service_id?: number
        service_meta_type?: string
        comment?: string
        id?: number
        project?: string
        data?: string
        extra_data?: {}
        env?: string
        created_time?: number
        created_by?: string
      }[]
      /**
       * 请求业务结果
       */
      success: boolean
      total_count?: number
    }
  }

  /**
   * Interface name：Add a deployment zone to this config
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6143
   */
  'POST/v1/depconf/config/add_deployment_zone': {
    Req: {
      /**
       * Project is a combination of $project-$module
       */
      project?: string
      /**
       * CMDB Service ID
       */
      service_id?: number
      zones?: {
        definition?: {
          envs?: {
            container?: {
              resources?: {
                cpu?: number
                disk?: number
                gpu?: number
                mem?: number
                skip_mem_limit_check?: boolean
              }
              scheduler?: {
                assignment_policies?: {
                  name?: string
                  parameters?: {
                    /**
                     * Only `agent_id` is supported so far.
                     */
                    unique_key?: string
                    max_instances?: number
                    selectors?: {
                      value?: string
                      key?: string
                      values?: unknown[]
                      operator?: string
                    }[]
                  }
                }[]
              }
              canary?: {
                multi_stage?: {
                  final?: string
                  stages?: unknown[]
                }
                instances?: string
                mode?: string
              }
              enabled?: boolean
              instances?: number
              minimum_instances?: number
              strategy?: {
                name?: string
                parameters?: {
                  canary_stages?: unknown[]
                  disable_restart?: boolean
                  enable_canary_replacement?: boolean
                  in_place?: boolean
                  max_surge?: string
                  max_unavailable?: string
                  reserve_resources?: boolean
                  step_down?: number
                  strict_in_place?: boolean
                  threshold?: number
                  instances_per_agent?: number
                }
              }
            }
            env?: string
            static_files?: {
              enabled?: boolean
            }
          }[]
        }
        dz_type?: string
        zone_id?: number
      }[]
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      bound_zones?: {
        id?: number
        zone_type?: string
        zone_val?: number
        full_name?: string
        envs?: unknown[]
        name?: string
        namespace?: string
      }[]
      /**
       * 请求业务结果
       */
      success: boolean
    }
  }

  /**
   * Interface name：Retrieves a field from multiple services
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6144
   */
  'POST/v1/depconf/config/bulk_get_field': {
    Req: {
      env?: string
      fields?: unknown[]
      limit?: number
      next_id?: number
      project_modules?: unknown[]
      service_ids?: unknown[]
      service_meta_type?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      configs?: {
        data?: {
          annotations?: {}
          strategy?: {
            parameters?: {
              canary_stages?: unknown[]
              instances_per_agent?: number
              enable_canary_replacement?: boolean
              disable_restart?: boolean
              in_place?: boolean
              max_surge?: string
              max_unavailable?: string
              strict_in_place?: boolean
              reserve_resources?: boolean
              threshold?: number
              step_down?: number
            }
            name?: string
          }
          instances?: number
          canary_percent?: number
          minimum_instances?: number
          canary_instances?: number
          scheduler?: {
            assignment_policies?: {
              name?: string
              parameters?: {
                /**
                 * Only `agent_id` is supported so far.
                 */
                unique_key?: string
                max_instances?: number
                selectors?: {
                  value?: string
                  key?: string
                  operator?: string
                  values?: unknown[]
                }[]
              }
            }[]
            orchestrator?: string
          }
          resources?: {
            cpu?: number
            disk?: number
            mem?: number
            gpu?: number
          }
        }
        service_id?: number
        az?: string
        cid?: string
        project_module?: string
        env?: string
      }[]
    }
  }

  /**
   * Interface name：Deletes all configs for this service
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6145
   */
  'POST/v1/depconf/config/delete': {
    Req: {
      email?: string
      project?: string
      service_id?: number
      service_meta_type?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      /**
       * 请求业务结果
       */
      success: boolean
    }
  }

  /**
   * Interface name：Delete deployment zones from this config
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6146
   */
  'POST/v1/depconf/config/delete_deployment_zone': {
    Req: {
      /**
       * Deployment zone IDs to delete
       */
      dz_type: string
      project?: string
      /**
       * CMDB Service ID
       */
      service_id?: number
      zone_ids?: unknown[]
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      /**
       * 请求业务结果
       */
      success: boolean
    }
  }

  /**
   * Interface name：Get all configs
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6147
   */
  'GET/v1/depconf/config/get_all': {
    Req: {
      /**
       * Environment to retrieve from
       */
      env?: string
      /**
       * Next config ID to retrieve from (default: 0)
       */
      next_id?: number
      /**
       * How many records to return (default: 50)
       */
      limit?: number
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      configurations?: {
        comment?: string
        data?: string
        commit_id?: number
        created_ts?: number
        deleted_at?: number
        service_meta_type?: string
        created_by?: string
        env?: string
        extra_data?: {}
        id?: number
        modified_by?: string
        modified_ts?: number
        project?: string
        service_id?: number
      }[]
      meta?: {
        has_next?: boolean
        next_id?: number
      }
      /**
       * 请求业务结果
       */
      success: boolean
      total_count?: number
    }
  }

  /**
   * Interface name：Get config cids
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6148
   */
  'GET/v1/depconf/config/get_cids': {
    Req: {
      /**
       * Project module name (smm-api). Specify this or service_id
       */
      project?: string
      /**
       * CMDB Service ID. Specify this or project
       */
      service_id?: string
      /**
       * environment
       */
      env: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      cids: string[]
      /**
       * 请求业务结果
       */
      success: boolean
    }
  }

  /**
   * Interface name：Get generated service config
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6149
   */
  'GET/v1/depconf/config/get_generated': {
    Req: {
      /**
       * Project module name (smm-api). Specify this or service_id
       */
      project?: string
      /**
       * CMDB Service ID. Specify this or project
       */
      service_id?: string
      /**
       * environment
       */
      env: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      configurations?: {
        commit_id?: number
        env?: string
        comment?: string
        data?: string
        service_meta_type?: string
        created_by?: string
        created_ts?: number
        deleted_at?: number
        extra_data?: {}
        project?: string
        id?: number
        service_id?: number
        modified_by?: string
        modified_ts?: number
      }[]
      /**
       * 请求业务结果
       */
      success: boolean
      total_count?: number
    }
  }

  /**
   * Interface name：Get service config
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6150
   */
  'GET/v1/depconf/config/get_info': {
    Req: {
      /**
       * Project module name (smm-api). Specify this or service_id
       */
      project?: string
      /**
       * CMDB Service ID. Specify this or project
       */
      service_id?: string
      /**
       * environment
       */
      env: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      configurations?: {
        comment?: string
        created_by?: string
        commit_id?: number
        service_meta_type?: string
        created_ts?: number
        extra_data?: {}
        deleted_at?: number
        data?: string
        env?: string
        project?: string
        modified_by?: string
        modified_ts?: number
        service_id?: number
        id?: number
      }[]
      /**
       * 请求业务结果
       */
      success: boolean
      total_count?: number
    }
  }

  /**
   * Interface name：Returns minimum instance count for this service
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6151
   */
  'GET/v1/depconf/config/get_minimum_instance': {
    Req: {
      /**
       * Project module name (smm-api)
       */
      project?: string
      /**
       * environment
       */
      env: string
      /**
       * cid
       */
      cid: string
      /**
       * az
       */
      az: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      /**
       * 请求业务结果
       */
      success: boolean
      value?: number
    }
  }

  /**
   * Interface name：List deployment zones this config is apart of
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6152
   */
  'GET/v1/depconf/config/list_deployment_zone': {
    Req: {
      /**
       * Project module name (smm-api). Specify this or service_id
       */
      project?: string
      /**
       * CMDB Service ID. Specify this or project
       */
      service_id?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      /**
       * 请求业务结果
       */
      success: boolean
      zones?: {
        full_name?: string
        envs?: unknown[]
        id?: number
        name?: string
        namespace?: string
        zone_type?: string
        zone_val?: number
      }[]
    }
  }

  /**
   * Interface name：Update idcs of a project
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6153
   */
  'POST/v1/depconf/config/update_idc': {
    Req: {
      cid: string
      comment?: string
      env: string
      idcs: unknown[]
      operation?: string
      project?: string
      service_id?: number
      service_meta_type?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {}
  }

  /**
   * Interface name：Update instance count for a project
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6154
   */
  'POST/v1/depconf/config/update_instance': {
    Req: {
      /**
       * project
       */
      project: string
      /**
       * env
       */
      env: string
      /**
       * cid
       */
      cid: string
      /**
       * idc
       */
      idc?: string
      /**
       * count
       */
      count: string
      /**
       * comment
       */
      comment?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {}
  }

  /**
   * Interface name：Update instances count for a project
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6155
   */
  'POST/v1/depconf/config/update_instances': {
    Req: {
      comment?: string
      email?: string
      env: string
      project?: string
      requests?: {
        cid: string
        count: number
        idc: string
      }[]
      service_id?: number
      service_meta_type?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {}
  }

  /**
   * Interface name：Update orchestrator of a project
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6156
   */
  'POST/v1/depconf/config/update_orchestrator': {
    Req: {
      cid?: string
      email?: string
      env?: string
      idcs?: unknown[]
      orchestrator?: string
      project?: string
      service_id?: number
      service_meta_type?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {}
  }

  /**
   * Interface name：Update overcommit factors and policy count for a project
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6157
   */
  'POST/v1/depconf/config/update_overcommits': {
    Req: {
      comment?: string
      email?: string
      env: string
      project?: string
      requests?: {
        idc: string
        cid: string
        overcommit_factor: number
        usage_class?: string
        overcommit_policy: string
      }[]
      service_id?: number
      service_meta_type?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {}
  }

  /**
   * Interface name：Update resource project
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6158
   */
  'POST/v1/depconf/config/update_resource': {
    Req: {
      comment?: string
      cpu: number
      env: string
      mem: number
      project?: string
      service_id?: number
      service_meta_type?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {}
  }

  /**
   * Interface name：getEnabledAutoSacle
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1004&itf=6011
   */
  'GET/apis/autoscaler/v1/service/acknowledgement_status': {
    Req: {
      project: string
      module: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      error_code: number
      error_message: string
      toggle_state: number
    }
  }

  /**
   * Interface name：get unbounded sdus
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1172&itf=7276
   */
  'GET/apis/cmdb/v2/service/get_unbounded_sdus': {
    Req: {
      /**
       * APP/CONTAINER/PHYSICAL/STATIC
       * 默认APP
       */
      resource_type?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      sdus: {
        sdu: string
        resource_type: string
        env: string
        cid: string
        idcs: unknown[]
        version: string
        deployment_link: string
        label: {}
        created_at: number
        updated_at: number
      }[]
      total_size: number
    }
  }

  /**
   * Interface name：bind sdus
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1172&itf=7277
   */
  'POST/apis/cmdb/v2/service/bind_sdu': {
    Req: {
      service_name: string
      /**
       * CONTAINER / PHYSICAL / STATIC / AUTODISCOVERY
       *
       */
      resource_type: string
      sdu: string
      /**
       * 默认false
       */
      force?: boolean
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      bounded: {
        service: {
          service_id: number
          service_name: string
          data: {
            spexible: string
          }
          updated_by: string
          service_owners: unknown[]
          enabled: boolean
          created_at: number
          updated_at: number
        }
        sdu: {
          sdu: string
          sdu_type: string
          env: string
          cid: string
          idcs: string[]
          version: string
          deployment_link: string
          label: {}
          created_at: number
          updated_at: number
        }
        bind: {
          service_sdu_relation_id: number
          service_id: number
          sdu_id: number
          enabled: boolean
          created_at: number
          updated_at: number
        }
      }[]
    }
  }

  /**
   * Interface name：unbind sdu
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1172&itf=7278
   */
  'POST/apis/cmdb/v2/service/unbind_sdu': {
    Req: {
      service_name: string
      /**
       * CONTAINER / PHYSICAL / STATIC / AUTODISCOVERY
       */
      resource_type: string
      sdu: string
      /**
       * 默认false
       */
      force?: boolean
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      unbounded: {
        service: {
          service_id: number
          service_name: string
          data: {
            spexible: string
          }
          updated_by: string
          service_owners: unknown[]
          enabled: boolean
          created_at: number
          updated_at: number
        }
        sdu: {
          sdu: string
          resource_type: string
          env: string
          cid: string
          idcs: string[]
          version: string
          deployment_link: string
          label: {}
          created_at: number
          updated_at: number
        }
        unbind: {
          service_sdu_relation_id: number
          service_id: number
          sdu_id: number
          enabled: boolean
          created_at: number
          updated_at: number
        }
      }[]
    }
  }

  /**
   * Interface name：test
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1172&itf=8887
   */
  'GET/test': {
    Req: {
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {}
  }

  /**
   * Interface name：get envs
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1189&itf=7313
   */
  'GET/apis/envs/v2/get_envs': {
    Req: {
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      result: {
        name: string
        alias_name: string
        enum_value: number
      }[]
    }
  }

  /**
   * Interface name：get cids
   * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1189&itf=11439
   */
  'GET/apis/envs/v2/get_cids': {
    Req: {
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      result: {
        name: string
        alias_name: string
        enum_value: number
        visible: boolean
      }[]
    }
  }
}

type ResSelector<T> = T

export interface IResponseTypes {
  'POST/v1/depconf/binding/bind_service': ResSelector<IModels['POST/v1/depconf/binding/bind_service']['Res']>
  'GET/v1/depconf/binding/list': ResSelector<IModels['GET/v1/depconf/binding/list']['Res']>
  'POST/v1/depconf/binding/unbind_service': ResSelector<IModels['POST/v1/depconf/binding/unbind_service']['Res']>
  'POST/apis/cmdb/v1/depconf/commit/copy_to': ResSelector<IModels['POST/apis/cmdb/v1/depconf/commit/copy_to']['Res']>
  'POST/apis/cmdb/v1/depconf/commit/create': ResSelector<IModels['POST/apis/cmdb/v1/depconf/commit/create']['Res']>
  'GET/apis/cmdb/v1/depconf/commit/get_info': ResSelector<IModels['GET/apis/cmdb/v1/depconf/commit/get_info']['Res']>
  'GET/apis/cmdb/v1/depconf/commit/get_latest_changes': ResSelector<
    IModels['GET/apis/cmdb/v1/depconf/commit/get_latest_changes']['Res']
  >
  'POST/v1/depconf/config/add_deployment_zone': ResSelector<
    IModels['POST/v1/depconf/config/add_deployment_zone']['Res']
  >
  'POST/v1/depconf/config/bulk_get_field': ResSelector<IModels['POST/v1/depconf/config/bulk_get_field']['Res']>
  'POST/v1/depconf/config/delete': ResSelector<IModels['POST/v1/depconf/config/delete']['Res']>
  'POST/v1/depconf/config/delete_deployment_zone': ResSelector<
    IModels['POST/v1/depconf/config/delete_deployment_zone']['Res']
  >
  'GET/v1/depconf/config/get_all': ResSelector<IModels['GET/v1/depconf/config/get_all']['Res']>
  'GET/v1/depconf/config/get_cids': ResSelector<IModels['GET/v1/depconf/config/get_cids']['Res']>
  'GET/v1/depconf/config/get_generated': ResSelector<IModels['GET/v1/depconf/config/get_generated']['Res']>
  'GET/v1/depconf/config/get_info': ResSelector<IModels['GET/v1/depconf/config/get_info']['Res']>
  'GET/v1/depconf/config/get_minimum_instance': ResSelector<
    IModels['GET/v1/depconf/config/get_minimum_instance']['Res']
  >
  'GET/v1/depconf/config/list_deployment_zone': ResSelector<
    IModels['GET/v1/depconf/config/list_deployment_zone']['Res']
  >
  'POST/v1/depconf/config/update_idc': ResSelector<IModels['POST/v1/depconf/config/update_idc']['Res']>
  'POST/v1/depconf/config/update_instance': ResSelector<IModels['POST/v1/depconf/config/update_instance']['Res']>
  'POST/v1/depconf/config/update_instances': ResSelector<IModels['POST/v1/depconf/config/update_instances']['Res']>
  'POST/v1/depconf/config/update_orchestrator': ResSelector<
    IModels['POST/v1/depconf/config/update_orchestrator']['Res']
  >
  'POST/v1/depconf/config/update_overcommits': ResSelector<IModels['POST/v1/depconf/config/update_overcommits']['Res']>
  'POST/v1/depconf/config/update_resource': ResSelector<IModels['POST/v1/depconf/config/update_resource']['Res']>
  'GET/apis/autoscaler/v1/service/acknowledgement_status': ResSelector<
    IModels['GET/apis/autoscaler/v1/service/acknowledgement_status']['Res']
  >
  'GET/apis/cmdb/v2/service/get_unbounded_sdus': ResSelector<
    IModels['GET/apis/cmdb/v2/service/get_unbounded_sdus']['Res']
  >
  'POST/apis/cmdb/v2/service/bind_sdu': ResSelector<IModels['POST/apis/cmdb/v2/service/bind_sdu']['Res']>
  'POST/apis/cmdb/v2/service/unbind_sdu': ResSelector<IModels['POST/apis/cmdb/v2/service/unbind_sdu']['Res']>
  'GET/test': ResSelector<IModels['GET/test']['Res']>
  'GET/apis/envs/v2/get_envs': ResSelector<IModels['GET/apis/envs/v2/get_envs']['Res']>
  'GET/apis/envs/v2/get_cids': ResSelector<IModels['GET/apis/envs/v2/get_cids']['Res']>
}

type RequestMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'OPTIONS' | 'PATCH' | 'HEAD'

export function createFetch(fetchConfig: commonLib.RequesterOption, extraConfig?: {fetchType?: commonLib.FetchType}) {
  if (!extraConfig || !extraConfig.fetchType) {
    console.warn(
      'Rapper Warning: createFetch API will be deprecated, if you want to customize fetch, please use overrideFetch instead, since new API guarantees better type consistency during frontend lifespan. See detail https://www.yuque.com/rap/rapper/overridefetch'
    )
  }
  const rapperFetch = commonLib.getRapperRequest(fetchConfig)

  function fetchMethod<T extends keyof IModels>(name: T) {
    type Method = T extends `${infer U}/${string}` ? U : never
    type URL = T extends `${RequestMethod}${infer U}` ? U : never
    const idx = name.indexOf('/')
    const method: Method = name.substring(0, idx)
    const url: URL = name.substring(idx)

    return (req?: IModels[T]['Req'], extra?: commonLib.IExtra) => {
      extra = extra || {}
      extra.reqType = {...(extra.reqType || {}), ...IReqType[name]}
      return rapperFetch({
        url,
        method,
        params: req,
        extra,
      }) as Promise<IResponseTypes[T]>
    }
  }

  return {
    /**
     * Interface name：Binds a cmdb service to a project
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1023&itf=6136
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/v1/depconf/binding/bind_service': fetchMethod('POST/v1/depconf/binding/bind_service'),

    /**
     * Interface name：List all bound services
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1023&itf=6137
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/v1/depconf/binding/list': fetchMethod('GET/v1/depconf/binding/list'),

    /**
     * Interface name：Binds a cmdb service to a project
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1023&itf=6138
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/v1/depconf/binding/unbind_service': fetchMethod('POST/v1/depconf/binding/unbind_service'),

    /**
     * Interface name：Copy a commit  to other environment
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1024&itf=6139
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/apis/cmdb/v1/depconf/commit/copy_to': fetchMethod('POST/apis/cmdb/v1/depconf/commit/copy_to'),

    /**
     * Interface name：Create a commit
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1024&itf=6140
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/apis/cmdb/v1/depconf/commit/create': fetchMethod('POST/apis/cmdb/v1/depconf/commit/create'),

    /**
     * Interface name：Get commits
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1024&itf=6141
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/apis/cmdb/v1/depconf/commit/get_info': fetchMethod('GET/apis/cmdb/v1/depconf/commit/get_info'),

    /**
     * Interface name：Get latest few commits in an environment
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1024&itf=6142
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/apis/cmdb/v1/depconf/commit/get_latest_changes': fetchMethod(
      'GET/apis/cmdb/v1/depconf/commit/get_latest_changes'
    ),

    /**
     * Interface name：Add a deployment zone to this config
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6143
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/v1/depconf/config/add_deployment_zone': fetchMethod('POST/v1/depconf/config/add_deployment_zone'),

    /**
     * Interface name：Retrieves a field from multiple services
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6144
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/v1/depconf/config/bulk_get_field': fetchMethod('POST/v1/depconf/config/bulk_get_field'),

    /**
     * Interface name：Deletes all configs for this service
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6145
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/v1/depconf/config/delete': fetchMethod('POST/v1/depconf/config/delete'),

    /**
     * Interface name：Delete deployment zones from this config
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6146
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/v1/depconf/config/delete_deployment_zone': fetchMethod('POST/v1/depconf/config/delete_deployment_zone'),

    /**
     * Interface name：Get all configs
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6147
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/v1/depconf/config/get_all': fetchMethod('GET/v1/depconf/config/get_all'),

    /**
     * Interface name：Get config cids
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6148
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/v1/depconf/config/get_cids': fetchMethod('GET/v1/depconf/config/get_cids'),

    /**
     * Interface name：Get generated service config
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6149
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/v1/depconf/config/get_generated': fetchMethod('GET/v1/depconf/config/get_generated'),

    /**
     * Interface name：Get service config
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6150
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/v1/depconf/config/get_info': fetchMethod('GET/v1/depconf/config/get_info'),

    /**
     * Interface name：Returns minimum instance count for this service
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6151
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/v1/depconf/config/get_minimum_instance': fetchMethod('GET/v1/depconf/config/get_minimum_instance'),

    /**
     * Interface name：List deployment zones this config is apart of
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6152
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/v1/depconf/config/list_deployment_zone': fetchMethod('GET/v1/depconf/config/list_deployment_zone'),

    /**
     * Interface name：Update idcs of a project
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6153
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/v1/depconf/config/update_idc': fetchMethod('POST/v1/depconf/config/update_idc'),

    /**
     * Interface name：Update instance count for a project
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6154
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/v1/depconf/config/update_instance': fetchMethod('POST/v1/depconf/config/update_instance'),

    /**
     * Interface name：Update instances count for a project
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6155
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/v1/depconf/config/update_instances': fetchMethod('POST/v1/depconf/config/update_instances'),

    /**
     * Interface name：Update orchestrator of a project
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6156
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/v1/depconf/config/update_orchestrator': fetchMethod('POST/v1/depconf/config/update_orchestrator'),

    /**
     * Interface name：Update overcommit factors and policy count for a project
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6157
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/v1/depconf/config/update_overcommits': fetchMethod('POST/v1/depconf/config/update_overcommits'),

    /**
     * Interface name：Update resource project
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1025&itf=6158
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/v1/depconf/config/update_resource': fetchMethod('POST/v1/depconf/config/update_resource'),

    /**
     * Interface name：getEnabledAutoSacle
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1004&itf=6011
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/apis/autoscaler/v1/service/acknowledgement_status': fetchMethod(
      'GET/apis/autoscaler/v1/service/acknowledgement_status'
    ),

    /**
     * Interface name：get unbounded sdus
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1172&itf=7276
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/apis/cmdb/v2/service/get_unbounded_sdus': fetchMethod('GET/apis/cmdb/v2/service/get_unbounded_sdus'),

    /**
     * Interface name：bind sdus
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1172&itf=7277
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/apis/cmdb/v2/service/bind_sdu': fetchMethod('POST/apis/cmdb/v2/service/bind_sdu'),

    /**
     * Interface name：unbind sdu
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1172&itf=7278
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/apis/cmdb/v2/service/unbind_sdu': fetchMethod('POST/apis/cmdb/v2/service/unbind_sdu'),

    /**
     * Interface name：test
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1172&itf=8887
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/test': fetchMethod('GET/test'),

    /**
     * Interface name：get envs
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1189&itf=7313
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/apis/envs/v2/get_envs': fetchMethod('GET/apis/envs/v2/get_envs'),

    /**
     * Interface name：get cids
     * Rap url: http://rap.shopee.io/repository/editor?id=225&mod=1189&itf=11439
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/apis/envs/v2/get_cids': fetchMethod('GET/apis/envs/v2/get_cids'),
  }
}
