/* md5: bff692ba58480722b71f7299f0304121 */
/* Rap repository id: 234 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=234
 */

export const IReqType = {}
