/* md5: 50b32f57149dae6fdd6174ea990d0055 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

export const IReqType = {
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:cancelcanary': {sduName: 2, deployId: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:editresource': {sduName: 2, deployId: 2, cpu: 2, memory: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:fullrelease': {sduName: 2, deployId: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:restart': {sduName: 2, deployId: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:rollback': {sduName: 2, deployId: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:scale': {sduName: 2, deployId: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:stop': {sduName: 2, deployId: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:suspend': {sduName: 2, deployId: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods/metrics': {sduName: 2, deployId: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods/{podName}:kill': {sduName: 2, deployId: 2, podName: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys:stop': {sduName: 2},
}
