/* md5: f01257ffd905ff704c2826d5bd82b58c */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

import * as commonLib from '@infra/rapper/runtime/commonLib'
import {IReqType} from './extra'

export interface IModels {
  /**
   * Interface name：ListAppClusterConfig
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8764
   */
  'GET/ecpapi/v2/appclusterconfig': {
    Req: {
      /**
       * If cmdb_tenant_id is non-empty, only return records under cmdb_tenant_id's tree
       */
      cmdbTenantId?: string
      pageNum?: number
      pageSize?: number
      /**
       * scope,key,env,az_key,segment_key,cid,cluster_uuid
       */
      filterBy?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      total?: string
      items?: {
        id?: string
        env?: string
        azKey?: string
        segmentKey?: string
        clusterUuid?: string
        scope?: string
        cmdbTenantId?: string
        key?: string
        cid?: string
      }[]
    }
  }

  /**
   * Interface name：AddAppClusterConfig
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8765
   */
  'POST/ecpapi/v2/appclusterconfig': {
    Req: {
      env?: string
      azKey?: string
      segmentKey?: string
      clusterUuid?: string
      scope?: string
      key?: string
      cmdbTenantId?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      id?: string
    }
  }

  /**
   * Interface name：RemoveAppClusterConfig
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8766
   */
  'DELETE/ecpapi/v2/appclusterconfig/{id}': {
    Req: {
      /**
       * scene key
       */
      __scene?: string
      id?: string
    }
    Res: {}
  }

  /**
   * Interface name：ListClusterDetail
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8767
   */
  'GET/ecpapi/v2/clusterdetails': {
    Req: {
      pageNum?: number
      pageSize?: number
      /**
       * support: cluster_type,az_key,segment_key,status,health
       */
      filterBy?: string
      /**
       * support: create_ts,node_count
       */
      orderBy?: string
      searchBy?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      total?: number
      items?: {
        meta?: {
          uuid?: string
          displayName?: string
          kubeConfig?: string
          azV1?: string
          azV2?: string
          regionKey?: string
          segmentKey?: string
          monitoringUrl?: string
          kubeApiserverType?: string
          ecpVersion?: string
          handleByGalio?: boolean
          platform?: string
          clusterType?: string
          karmadaKubeConfig?: string
          labels?: string[]
          descriptions?: string
          createTs?: string
          azForDepconf?: string
        }
        status?: {
          nodeSummary?: {
            capacity?: number
            count?: number
            unhealthyCount?: number
          }
          health?: string
          observabilityLink?: string
          status?: string
          alarms?: {
            type?: string
            resourceName?: string
            message?: string
            title?: string
          }[]
          podSummary?: {
            count?: number
            unhealthyCount?: number
            capacity?: number
          }
          metrics?: {
            cpu?: {
              reserved?: number
              assigned?: number
              free?: number
              used?: number
              assignedUsage?: number
              capacity?: number
              workerAllocatable?: number
              allocatable?: number
              usedUsage?: number
            }
            memory?: {
              assigned?: number
              used?: number
              assignedUsage?: number
              workerAllocatable?: number
              usedUsage?: number
              allocatable?: number
              capacity?: number
              reserved?: number
              free?: number
            }
            disk?: {
              capacity?: number
              free?: number
              used?: number
              usedUsage?: number
              assignedUsage?: number
              reserved?: number
              assigned?: number
              workerAllocatable?: number
              allocatable?: number
            }
            gpu?: {
              capacity?: number
              reserved?: number
              used?: number
              assigned?: number
              free?: number
              usedUsage?: number
              allocatable?: number
              workerAllocatable?: number
              assignedUsage?: number
            }
          }
        }
      }[]
    }
  }

  /**
   * Interface name：ListClusterMeta
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8768
   */
  'GET/ecpapi/v2/clustermetas': {
    Req: {
      pageNum?: number
      pageSize?: number
      /**
       * cluster_type,az_key,segment_key
       */
      filterBy?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      total?: number
      items?: {
        descriptions?: string
        createTs?: string
        regionKey?: string
        azV1?: string
        platform?: string
        segmentKey?: string
        azV2?: string
        clusterType?: string
        karmadaKubeConfig?: string
        uuid?: string
        ecpVersion?: string
        kubeApiserverType?: string
        kubeConfig?: string
        labels?: string[]
        monitoringUrl?: string
        displayName?: string
        azForDepconf?: string
        handleByGalio?: boolean
      }[]
    }
  }

  /**
   * Interface name：AddClusterMeta
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8769
   */
  'POST/ecpapi/v2/clustermetas': {
    Req: {
      uuid?: string
      displayName?: string
      kubeConfig?: string
      azV1?: string
      azV2?: string
      segmentKey?: string
      monitoringUrl?: string
      /**
       * If empty, default value equal to "native",
       * more enums seeing https://{ecp-openapi-domain}/ecpapi/v2/enums.
       */
      kubeApiserverType?: string
      /**
       * ecpv1: only native capability,
       * leap: support bromo,
       * ecpv2: support bromo & native capability,
       * If empty, default value equal to "ecpv2",
       * more enums seeing https://{ecp-openapi-domain}/ecpapi/v2/enums.
       */
      ecpVersion?: string
      handleByGalio?: boolean
      /**
       * If empty, default value equal to "az",
       * more enums seeing https://{ecp-openapi-domain}/ecpapi/v2/enums.
       */
      platform?: string
      /**
       * If empty, default value equal to "cis",
       * more enums seeing https://{ecp-openapi-domain}/ecpapi/v2/enums.
       */
      clusterType?: string
      karmadaKubeConfig?: string
      labels?: string[]
      descriptions?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {}
  }

  /**
   * Interface name：QueryClusterDetail
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8770
   */
  'GET/ecpapi/v2/clusters/{uuid}/detail': {
    Req: {
      uuid: string
      needStatus?: boolean
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      detail?: {
        meta?: {
          uuid?: string
          displayName?: string
          ecpVersion?: string
          kubeApiserverType?: string
          kubeConfig?: string
          azV1?: string
          azV2?: string
          segmentKey?: string
          regionKey?: string
          labels?: string[]
          descriptions?: string
          createTs?: string
          azForDepconf?: string
          handleByGalio?: boolean
          platform?: string
          clusterType?: string
          karmadaKubeConfig?: string
          monitoringUrl?: string
        }
        status?: {
          podSummary?: {
            capacity?: number
            count?: number
            unhealthyCount?: number
          }
          nodeSummary?: {
            capacity?: number
            count?: number
            unhealthyCount?: number
          }
          status?: string
          alarms?: {
            type?: string
            resourceName?: string
            message?: string
            title?: string
          }[]
          health?: string
          metrics?: {
            memory?: {
              capacity?: number
              reserved?: number
              assignedUsage?: number
              usedUsage?: number
              workerAllocatable?: number
              allocatable?: number
              assigned?: number
              free?: number
              used?: number
            }
            disk?: {
              capacity?: number
              assigned?: number
              free?: number
              reserved?: number
              usedUsage?: number
              allocatable?: number
              used?: number
              assignedUsage?: number
              workerAllocatable?: number
            }
            cpu?: {
              assigned?: number
              capacity?: number
              reserved?: number
              free?: number
              used?: number
              usedUsage?: number
              assignedUsage?: number
              workerAllocatable?: number
              allocatable?: number
            }
            gpu?: {
              workerAllocatable?: number
              allocatable?: number
              capacity?: number
              assignedUsage?: number
              reserved?: number
              assigned?: number
              usedUsage?: number
              used?: number
              free?: number
            }
          }
          observabilityLink?: string
        }
      }
    }
  }

  /**
   * Interface name：ListClusterNodes
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8771
   */
  'GET/ecpapi/v2/clusters/{uuid}/nodes': {
    Req: {
      uuid: string
      pageNum?: number
      pageSize?: number
      /**
       * support: status,role,label_key,label_value,
       */
      filterBy?: string
      /**
       * support: todo
       */
      orderBy?: string
      searchBy?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      total?: number
      nodes?: {
        name?: string
        podSummary?: {
          capacity?: number
          count?: number
          unhealthyCount?: number
        }
        status?: string
        metrics?: {
          cpu?: {
            capacity?: number
            assigned?: number
            free?: number
            used?: number
            workerAllocatable?: number
            allocatable?: number
            reserved?: number
            usedUsage?: number
            assignedUsage?: number
          }
          memory?: {
            capacity?: number
            assignedUsage?: number
            reserved?: number
            assigned?: number
            free?: number
            used?: number
            usedUsage?: number
            allocatable?: number
            workerAllocatable?: number
          }
          disk?: {
            reserved?: number
            usedUsage?: number
            assignedUsage?: number
            workerAllocatable?: number
            allocatable?: number
            capacity?: number
            free?: number
            used?: number
            assigned?: number
          }
          gpu?: {
            free?: number
            workerAllocatable?: number
            allocatable?: number
            reserved?: number
            capacity?: number
            assigned?: number
            used?: number
            usedUsage?: number
            assignedUsage?: number
          }
        }
        privateIp?: string
        labels?: {
          key?: string
          value?: string
        }[]
        roles?: string[]
        taints?: {
          value?: string
          effect?: string
          key?: string
        }[]
      }[]
      summary?: {
        readyCount?: number
        notReadyCount?: number
        unknownCount?: number
        total?: number
      }
      roles?: string[]
    }
  }

  /**
   * Interface name：ListAzDetail
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1386&itf=8772
   */
  'GET/ecpapi/v2/azs': {
    Req: {
      env?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      items?: {
        name?: string
        capability?: string[]
        env?: string
        clusters?: string[]
        version?: string
        azKey?: string
      }[]
    }
  }

  /**
   * Interface name：QueryAZMapping
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1386&itf=8773
   */
  'GET/ecpapi/v2/azs/{azKey}/mapping': {
    Req: {
      azKey: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      version?: string
      items?: {
        version?: string
        azKey?: string
      }[]
    }
  }

  /**
   * Interface name：HealthCheck
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1387&itf=8774
   */
  'GET/ecpapi/v2/check': {
    Req: {
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      app?: string
      message?: string
    }
  }

  /**
   * Interface name：GetDeploymentHistory
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=9605
   */
  'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/deploy_history': {
    Req: {
      sduName: string
      deployId: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      list?: {
        containers?: {
          image?: string
          phase?: string
          tag?: string
          name?: string
          timestamp?: string
        }[]
        deploymentId?: string
        state?: string
        lastDeployed?: number
      }[]
    }
  }

  /**
   * Interface name：GetDeploymentPreview
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=9606
   */
  'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/deploy_preview': {
    Req: {
      sduName: string
      deployId: string
      deploymentId?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      old?: {
        az?: string
        totalInstances?: string
        tag?: string
      }
      new?: {
        az?: string
        tag?: string
        totalInstances?: string
      }
    }
  }

  /**
   * Interface name：CreateDeployment
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8775
   */
  'POST/ecpapi/v2/deployments': {
    Req: {
      metadata?: {
        bundle?: string
        serviceName?: string
        project?: string
        module?: string
        env?: string
        cluster?: string
        az?: string
        cid?: string
        feature?: string
      }
      components?: {
        type?: string
        settings?: string
        traits?: {
          settings?: string
          type?: string
        }[]
      }[]
      canary?: boolean
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      deployId?: string
    }
  }

  /**
   * Interface name：ListServiceDeployments
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8776
   */
  'GET/ecpapi/v2/sdus/{sduName}/svcdeploys': {
    Req: {
      sduName: string
      withdetail?: boolean
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      items?: {
        deployId?: string
        project?: string
        module?: string
        cluster?: string
        clusterType?: string
        sduName?: string
        summary?: {
          cpu?: number
          runningInstances?: number
          stagingInstances?: number
          targetInstances?: number
          unhealthyInstances?: number
          mem?: number
          healthyInstances?: number
          killingInstances?: number
          unknownInstances?: number
          releaseInstances?: number
          canaryInstances?: number
          state?: string
          lastDeployed?: number
          sduName?: string
          startingInstances?: number
          disk?: number
        }
        status?: {
          reason?: string
          orchestrator?: string
          containers?: {
            name?: string
            image?: string
            phase?: string
            tag?: string
            timestamp?: string
          }[]
        }
        env?: string
        cid?: string
        feature?: string
        bundle?: string
        azV1?: string
        azV2?: string
        deployEngine?: string
        componentType?: string
      }[]
      total?: number
    }
  }

  /**
   * Interface name：ListDeployHistory
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8777
   */
  'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/history': {
    Req: {
      sduName: string
      deployId: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      totalSize?: number
      items?: {
        summary?: {}
        status?: {}
      }[]
    }
  }

  /**
   * Interface name：GetServiceDeploymentMeta
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8778
   */
  'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/meta': {
    Req: {
      sduName: string
      deployId: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      deployment?: {
        deployId?: string
        project?: string
        env?: string
        sduName?: string
        module?: string
        cid?: string
        deployEngine?: string
        feature?: string
        bundle?: string
        componentType?: string
        summary?: {
          cpu?: number
          mem?: number
          disk?: number
          healthyInstances?: number
          runningInstances?: number
          stagingInstances?: number
          killingInstances?: number
          canaryInstances?: number
          startingInstances?: number
          targetInstances?: number
          unhealthyInstances?: number
          unknownInstances?: number
          releaseInstances?: number
          state?: string
          lastDeployed?: number
          sduName?: string
        }
        status?: {
          reason?: string
          orchestrator?: string
          containers?: {
            image?: string
            name?: string
            phase?: string
            timestamp?: string
            tag?: string
          }[]
        }
        azV2?: string
        cluster?: string
        clusterType?: string
        azV1?: string
      }
    }
  }

  /**
   * Interface name：GetDeploymentResult
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8779
   */
  'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/result': {
    Req: {
      sduName: string
      deployId: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      status?: {}
      reason?: string
    }
  }

  /**
   * Interface name：DeploymentCancelCanary
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8780
   */
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:cancelcanary': {
    Req: {
      sduName: string
      deployId: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {}
  }

  /**
   * Interface name：GetDeploymentHistory
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8781
   */
  'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:deploymentHistory': {
    Req: {
      sduName: string
      deployId: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      list?: {
        containers?: unknown[]
        deploymentId?: string
        state?: string
        lastDeployed?: number
      }[]
    }
  }

  /**
   * Interface name：GetDeploymentPreview
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8782
   */
  'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:deploymentPreview': {
    Req: {
      sduName: string
      deployId: string
      deploymentId?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      old?: {
        az?: string
        totalInstances?: string
        tag?: string
      }
      new?: {}
    }
  }

  /**
   * Interface name：DeploymentEditResource
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8783
   */
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:editresource': {
    Req: {
      sduName: string
      deployId: string
      cpu?: string
      memory?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {}
  }

  /**
   * Interface name：FullReleaseDeployment
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8784
   */
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:fullrelease': {
    Req: {
      sduName: string
      deployId: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {}
  }

  /**
   * Interface name：RestartDeployment
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8785
   */
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:restart': {
    Req: {
      sduName: string
      deployId: string
      phases?: string[]
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {}
  }

  /**
   * Interface name：RollbackDeployment
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8786
   */
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:rollback': {
    Req: {
      sduName: string
      deployId: string
      deploymentId?: string
      containers?: {
        name?: string
        image?: string
        tag?: string
        phase?: string
        timestamp?: string
      }[]
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {}
  }

  /**
   * Interface name：ScaleDeployment
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8787
   */
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:scale': {
    Req: {
      sduName: string
      deployId: string
      releaseReplicas?: number
      canaryReplicas?: number
      canaryValid?: boolean
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {}
  }

  /**
   * Interface name：Stop Deployment
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8788
   */
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:stop': {
    Req: {
      sduName: string
      deployId: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {}
  }

  /**
   * Interface name：SuspendDeployment
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8789
   */
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:suspend': {
    Req: {
      sduName: string
      deployId: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {}
  }

  /**
   * Interface name：ListWorkload
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8790
   */
  'GET/ecpapi/v2/workloads': {
    Req: {
      env?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      items?: {
        env?: string
        workloads?: {
          category?: string
          name?: string
          type?: string
          nameDisplay?: string
        }[]
        az?: string
      }[]
    }
  }

  /**
   * Interface name：QueryECPEnumerations
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1389&itf=8791
   */
  'GET/ecpapi/v2/enums': {
    Req: {
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      allenums?: {
        enums?: string[]
        type?: string
      }[]
    }
  }

  /**
   * Interface name：ListSDUHpasRequest
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1390&itf=8792
   */
  'GET/ecpapi/v2/sdus/{sduName}/hpas': {
    Req: {
      sduName: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      items?: {
        id?: number
        spec?: {
          triggerRules?: {
            type?: string
            cronRule?: {
              repeatType?: {}
              startTime?: string
              endWeekday?: {}
              endTime?: string
              targetCount?: number
              startWeekday?: {}
            }
            autoscalingRule?: {
              metrics?: string
              threshold?: number
            }
          }[]
          status?: number
          maxReplicaCount?: number
          minReplicaCount?: number
          notifyChannel?: string
          updatedTime?: string
          updator?: string
          behavior?: {
            scaleUp?: {
              stabilizationWindowSeconds?: number
              notifyFailed?: boolean
              selected?: boolean
            }
            scaleDown?: {
              stabilizationWindowSeconds?: number
              notifyFailed?: boolean
              selected?: boolean
            }
          }
          autoscalingLogic?: string
        }
        meta?: {
          sdu?: string
          az?: string
        }
      }[]
      total?: number
    }
  }

  /**
   * Interface name：GetPodsMetrics
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1391&itf=9607
   */
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods/metrics': {
    Req: {
      sduName: string
      deployId: string
      pods?: {
        podName?: string
        namespace?: string
      }[]
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      items?: {
        podName?: string
        namespace?: string
        cpu?: {
          used?: number
          applied?: number
        }
        memory?: {
          used?: number
          applied?: number
        }
      }[]
    }
  }

  /**
   * Interface name：ListSDUPods
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1391&itf=8793
   */
  'GET/ecpapi/v2/sdus/{sduName}/pods': {
    Req: {
      sduName: string
      /**
       * support filter by env、cid, Example: ?filter_by=env==testcid==CN
       */
      filterBy?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      items?: {
        nodeIp?: string
        podPort?: number
        podName?: string
        nodeName?: string
        createdTime?: number
        clusterName?: string
        namespace?: string
        tag?: string
        cid?: string
        lastRestartTime?: number
        idc?: string
        sdu?: string
        containerInfo?: {
          containerId?: string
          contianerName?: string
        }[]
        podIp?: string
        status?: string
        env?: string
        phase?: string
        restartCount?: number
      }[]
      total?: number
    }
  }

  /**
   * Interface name：GetSDUPod
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1391&itf=8794
   */
  'GET/ecpapi/v2/sdus/{sduName}/pods/{podName}': {
    Req: {
      sduName: string
      podName: string
      /**
       * support filter by env、cid, Example: ?filter_by=env==testcid==CN
       */
      filterBy?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      pod?: {
        podName?: string
        nodeName?: string
        sdu?: string
        nodeIp?: string
        restartCount?: number
        clusterName?: string
        namespace?: string
        cid?: string
        podIp?: string
        idc?: string
        podPort?: number
        status?: string
        containerInfo?: {
          containerId?: string
          contianerName?: string
        }[]
        phase?: string
        createdTime?: number
        tag?: string
        lastRestartTime?: number
        env?: string
      }
    }
  }

  /**
   * Interface name：ListDeploymentPods
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1391&itf=8795
   */
  'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods': {
    Req: {
      sduName: string
      deployId: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      items?: {
        podName?: string
        nodeName?: string
        namespace?: string
        clusterName?: string
        env?: string
        phase?: string
        idc?: string
        sdu?: string
        containerInfo?: {
          containerId?: string
          contianerName?: string
        }[]
        cid?: string
        nodeIp?: string
        podIp?: string
        status?: string
        podPort?: number
        createdTime?: number
        restartCount?: number
        tag?: string
        lastRestartTime?: number
      }[]
      total?: number
    }
  }

  /**
   * Interface name：Kill Pod
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1391&itf=8796
   */
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods/{podName}:kill': {
    Req: {
      sduName: string
      deployId: string
      podName: string
      clusterName?: string
      namespace?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {}
  }

  /**
   * Interface name：GetPodsMetrics
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1391&itf=8797
   */
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods:metrics': {
    Req: {
      /**
       * scene key
       */
      __scene?: string
      sduName?: string
      deployId?: string
      metrics?: string
    }
    Res: {
      items?: {
        podName?: string
        namespace?: string
        memory?: {}
        cpu?: {
          applied?: number
          used?: number
        }
      }[]
    }
  }

  /**
   * Interface name：GetSDUSummary
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1392&itf=8798
   */
  'GET/ecpapi/v2/sdus/{sduName}/summary': {
    Req: {
      sduName: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      summary?: {
        mem?: number
        healthyInstances?: number
        stagingInstances?: number
        cpu?: number
        state?: string
        lastDeployed?: number
        disk?: number
        sduName?: string
        killingInstances?: number
        runningInstances?: number
        startingInstances?: number
        targetInstances?: number
        releaseInstances?: number
        unknownInstances?: number
        canaryInstances?: number
        unhealthyInstances?: number
      }
    }
  }

  /**
   * Interface name：StopResourceBySdu
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1392&itf=8799
   */
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys:stop': {
    Req: {
      sduName: string
      /**
       * scene key
       */
      __scene?: string
      stop?: string
    }
    Res: {}
  }

  /**
   * Interface name：ListAllSDUsSummary
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1392&itf=8800
   */
  'GET/ecpapi/v2/services/sdus/summary': {
    Req: {
      sduName?: string
      /**
       * support filter by env、cid, Example: ?filter_by=env==testcid==CN
       */
      filterBy?: string
      /**
       * keyword to search, support sdu name
       */
      keyword?: string
      isGroup?: boolean
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      items?: {
        cpu?: number
        stagingInstances?: number
        startingInstances?: number
        unhealthyInstances?: number
        mem?: number
        disk?: number
        killingInstances?: number
        healthyInstances?: number
        lastDeployed?: number
        runningInstances?: number
        sduName?: string
        targetInstances?: number
        unknownInstances?: number
        canaryInstances?: number
        releaseInstances?: number
        state?: string
      }[]
      totalSize?: number
    }
  }

  /**
   * Interface name：ListServiceSDU
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1392&itf=8801
   */
  'GET/ecpapi/v2/services/{serviceName}/sdus': {
    Req: {
      serviceName: string
      /**
       * support filter by env、cid, Example: ?filter_by=env==testcid==CN
       */
      filterBy?: string
      /**
       * keyword to search, support sdu name
       */
      keyword?: string
      isGroup?: boolean
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      items?: {
        sduId?: number
        resourceType?: string
        cid?: string
        serviceId?: number
        sdu?: string
        env?: string
        version?: string
        deploymentLink?: string
        identifier?: {
          project?: string
          module?: string
        }
        idcs?: string[]
        serviceName?: string
      }[]
      totalSize?: number
    }
  }

  /**
   * Interface name：ListDeployZone
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1393&itf=8802
   */
  'GET/ecpapi/v2/service/{serviceName}/deployzones': {
    Req: {
      serviceName: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      totalSize?: number
      items?: {
        zoneName?: string
        az?: string
        description?: string
      }[]
    }
  }

  /**
   * Interface name：QueryECPTree
   * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1394&itf=8803
   */
  'GET/ecpapi/v2/tree/{rootType}/key/{rootKey}': {
    Req: {
      rootType: string
      rootKey: string
      /**
       * project,application
       */
      leafType?: string
      /**
       * scene key
       */
      __scene?: string
    }
    Res: {
      tree?: {
        rootType?: string
        rootKey?: string
        leafKey?: string[]
        leafType?: 'project' | 'application'
      }
    }
  }
}

type ResSelector<T> = T

export interface IResponseTypes {
  'GET/ecpapi/v2/appclusterconfig': ResSelector<IModels['GET/ecpapi/v2/appclusterconfig']['Res']>
  'POST/ecpapi/v2/appclusterconfig': ResSelector<IModels['POST/ecpapi/v2/appclusterconfig']['Res']>
  'DELETE/ecpapi/v2/appclusterconfig/{id}': ResSelector<IModels['DELETE/ecpapi/v2/appclusterconfig/{id}']['Res']>
  'GET/ecpapi/v2/clusterdetails': ResSelector<IModels['GET/ecpapi/v2/clusterdetails']['Res']>
  'GET/ecpapi/v2/clustermetas': ResSelector<IModels['GET/ecpapi/v2/clustermetas']['Res']>
  'POST/ecpapi/v2/clustermetas': ResSelector<IModels['POST/ecpapi/v2/clustermetas']['Res']>
  'GET/ecpapi/v2/clusters/{uuid}/detail': ResSelector<IModels['GET/ecpapi/v2/clusters/{uuid}/detail']['Res']>
  'GET/ecpapi/v2/clusters/{uuid}/nodes': ResSelector<IModels['GET/ecpapi/v2/clusters/{uuid}/nodes']['Res']>
  'GET/ecpapi/v2/azs': ResSelector<IModels['GET/ecpapi/v2/azs']['Res']>
  'GET/ecpapi/v2/azs/{azKey}/mapping': ResSelector<IModels['GET/ecpapi/v2/azs/{azKey}/mapping']['Res']>
  'GET/ecpapi/v2/check': ResSelector<IModels['GET/ecpapi/v2/check']['Res']>
  'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/deploy_history': ResSelector<
    IModels['GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/deploy_history']['Res']
  >
  'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/deploy_preview': ResSelector<
    IModels['GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/deploy_preview']['Res']
  >
  'POST/ecpapi/v2/deployments': ResSelector<IModels['POST/ecpapi/v2/deployments']['Res']>
  'GET/ecpapi/v2/sdus/{sduName}/svcdeploys': ResSelector<IModels['GET/ecpapi/v2/sdus/{sduName}/svcdeploys']['Res']>
  'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/history': ResSelector<
    IModels['GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/history']['Res']
  >
  'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/meta': ResSelector<
    IModels['GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/meta']['Res']
  >
  'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/result': ResSelector<
    IModels['GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/result']['Res']
  >
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:cancelcanary': ResSelector<
    IModels['POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:cancelcanary']['Res']
  >
  'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:deploymentHistory': ResSelector<
    IModels['GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:deploymentHistory']['Res']
  >
  'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:deploymentPreview': ResSelector<
    IModels['GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:deploymentPreview']['Res']
  >
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:editresource': ResSelector<
    IModels['POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:editresource']['Res']
  >
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:fullrelease': ResSelector<
    IModels['POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:fullrelease']['Res']
  >
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:restart': ResSelector<
    IModels['POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:restart']['Res']
  >
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:rollback': ResSelector<
    IModels['POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:rollback']['Res']
  >
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:scale': ResSelector<
    IModels['POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:scale']['Res']
  >
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:stop': ResSelector<
    IModels['POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:stop']['Res']
  >
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:suspend': ResSelector<
    IModels['POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:suspend']['Res']
  >
  'GET/ecpapi/v2/workloads': ResSelector<IModels['GET/ecpapi/v2/workloads']['Res']>
  'GET/ecpapi/v2/enums': ResSelector<IModels['GET/ecpapi/v2/enums']['Res']>
  'GET/ecpapi/v2/sdus/{sduName}/hpas': ResSelector<IModels['GET/ecpapi/v2/sdus/{sduName}/hpas']['Res']>
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods/metrics': ResSelector<
    IModels['POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods/metrics']['Res']
  >
  'GET/ecpapi/v2/sdus/{sduName}/pods': ResSelector<IModels['GET/ecpapi/v2/sdus/{sduName}/pods']['Res']>
  'GET/ecpapi/v2/sdus/{sduName}/pods/{podName}': ResSelector<
    IModels['GET/ecpapi/v2/sdus/{sduName}/pods/{podName}']['Res']
  >
  'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods': ResSelector<
    IModels['GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods']['Res']
  >
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods/{podName}:kill': ResSelector<
    IModels['POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods/{podName}:kill']['Res']
  >
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods:metrics': ResSelector<
    IModels['POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods:metrics']['Res']
  >
  'GET/ecpapi/v2/sdus/{sduName}/summary': ResSelector<IModels['GET/ecpapi/v2/sdus/{sduName}/summary']['Res']>
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys:stop': ResSelector<
    IModels['POST/ecpapi/v2/sdus/{sduName}/svcdeploys:stop']['Res']
  >
  'GET/ecpapi/v2/services/sdus/summary': ResSelector<IModels['GET/ecpapi/v2/services/sdus/summary']['Res']>
  'GET/ecpapi/v2/services/{serviceName}/sdus': ResSelector<IModels['GET/ecpapi/v2/services/{serviceName}/sdus']['Res']>
  'GET/ecpapi/v2/service/{serviceName}/deployzones': ResSelector<
    IModels['GET/ecpapi/v2/service/{serviceName}/deployzones']['Res']
  >
  'GET/ecpapi/v2/tree/{rootType}/key/{rootKey}': ResSelector<
    IModels['GET/ecpapi/v2/tree/{rootType}/key/{rootKey}']['Res']
  >
}

type RequestMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'OPTIONS' | 'PATCH' | 'HEAD'

export function createFetch(fetchConfig: commonLib.RequesterOption, extraConfig?: {fetchType?: commonLib.FetchType}) {
  if (!extraConfig || !extraConfig.fetchType) {
    console.warn(
      'Rapper Warning: createFetch API will be deprecated, if you want to customize fetch, please use overrideFetch instead, since new API guarantees better type consistency during frontend lifespan. See detail https://www.yuque.com/rap/rapper/overridefetch'
    )
  }
  const rapperFetch = commonLib.getRapperRequest(fetchConfig)

  function fetchMethod<T extends keyof IModels>(name: T) {
    type Method = T extends `${infer U}/${string}` ? U : never
    type URL = T extends `${RequestMethod}${infer U}` ? U : never
    const idx = name.indexOf('/')
    const method: Method = name.substring(0, idx)
    const url: URL = name.substring(idx)

    return (req?: IModels[T]['Req'], extra?: commonLib.IExtra) => {
      extra = extra || {}
      extra.reqType = {...(extra.reqType || {}), ...IReqType[name]}
      return rapperFetch({
        url,
        method,
        params: req,
        extra,
      }) as Promise<IResponseTypes[T]>
    }
  }

  return {
    /**
     * Interface name：ListAppClusterConfig
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8764
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/appclusterconfig': fetchMethod('GET/ecpapi/v2/appclusterconfig'),

    /**
     * Interface name：AddAppClusterConfig
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8765
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/ecpapi/v2/appclusterconfig': fetchMethod('POST/ecpapi/v2/appclusterconfig'),

    /**
     * Interface name：RemoveAppClusterConfig
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8766
     * @param req request parameters
     * @param extra request config parameters
     */
    'DELETE/ecpapi/v2/appclusterconfig/{id}': fetchMethod('DELETE/ecpapi/v2/appclusterconfig/{id}'),

    /**
     * Interface name：ListClusterDetail
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8767
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/clusterdetails': fetchMethod('GET/ecpapi/v2/clusterdetails'),

    /**
     * Interface name：ListClusterMeta
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8768
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/clustermetas': fetchMethod('GET/ecpapi/v2/clustermetas'),

    /**
     * Interface name：AddClusterMeta
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8769
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/ecpapi/v2/clustermetas': fetchMethod('POST/ecpapi/v2/clustermetas'),

    /**
     * Interface name：QueryClusterDetail
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8770
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/clusters/{uuid}/detail': fetchMethod('GET/ecpapi/v2/clusters/{uuid}/detail'),

    /**
     * Interface name：ListClusterNodes
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8771
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/clusters/{uuid}/nodes': fetchMethod('GET/ecpapi/v2/clusters/{uuid}/nodes'),

    /**
     * Interface name：ListAzDetail
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1386&itf=8772
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/azs': fetchMethod('GET/ecpapi/v2/azs'),

    /**
     * Interface name：QueryAZMapping
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1386&itf=8773
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/azs/{azKey}/mapping': fetchMethod('GET/ecpapi/v2/azs/{azKey}/mapping'),

    /**
     * Interface name：HealthCheck
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1387&itf=8774
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/check': fetchMethod('GET/ecpapi/v2/check'),

    /**
     * Interface name：GetDeploymentHistory
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=9605
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/deploy_history': fetchMethod(
      'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/deploy_history'
    ),

    /**
     * Interface name：GetDeploymentPreview
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=9606
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/deploy_preview': fetchMethod(
      'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/deploy_preview'
    ),

    /**
     * Interface name：CreateDeployment
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8775
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/ecpapi/v2/deployments': fetchMethod('POST/ecpapi/v2/deployments'),

    /**
     * Interface name：ListServiceDeployments
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8776
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/sdus/{sduName}/svcdeploys': fetchMethod('GET/ecpapi/v2/sdus/{sduName}/svcdeploys'),

    /**
     * Interface name：ListDeployHistory
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8777
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/history': fetchMethod(
      'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/history'
    ),

    /**
     * Interface name：GetServiceDeploymentMeta
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8778
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/meta': fetchMethod(
      'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/meta'
    ),

    /**
     * Interface name：GetDeploymentResult
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8779
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/result': fetchMethod(
      'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/result'
    ),

    /**
     * Interface name：DeploymentCancelCanary
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8780
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:cancelcanary': fetchMethod(
      'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:cancelcanary'
    ),

    /**
     * Interface name：GetDeploymentHistory
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8781
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:deploymentHistory': fetchMethod(
      'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:deploymentHistory'
    ),

    /**
     * Interface name：GetDeploymentPreview
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8782
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:deploymentPreview': fetchMethod(
      'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:deploymentPreview'
    ),

    /**
     * Interface name：DeploymentEditResource
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8783
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:editresource': fetchMethod(
      'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:editresource'
    ),

    /**
     * Interface name：FullReleaseDeployment
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8784
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:fullrelease': fetchMethod(
      'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:fullrelease'
    ),

    /**
     * Interface name：RestartDeployment
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8785
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:restart': fetchMethod(
      'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:restart'
    ),

    /**
     * Interface name：RollbackDeployment
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8786
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:rollback': fetchMethod(
      'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:rollback'
    ),

    /**
     * Interface name：ScaleDeployment
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8787
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:scale': fetchMethod(
      'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:scale'
    ),

    /**
     * Interface name：Stop Deployment
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8788
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:stop': fetchMethod(
      'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:stop'
    ),

    /**
     * Interface name：SuspendDeployment
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8789
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:suspend': fetchMethod(
      'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:suspend'
    ),

    /**
     * Interface name：ListWorkload
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8790
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/workloads': fetchMethod('GET/ecpapi/v2/workloads'),

    /**
     * Interface name：QueryECPEnumerations
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1389&itf=8791
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/enums': fetchMethod('GET/ecpapi/v2/enums'),

    /**
     * Interface name：ListSDUHpasRequest
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1390&itf=8792
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/sdus/{sduName}/hpas': fetchMethod('GET/ecpapi/v2/sdus/{sduName}/hpas'),

    /**
     * Interface name：GetPodsMetrics
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1391&itf=9607
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods/metrics': fetchMethod(
      'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods/metrics'
    ),

    /**
     * Interface name：ListSDUPods
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1391&itf=8793
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/sdus/{sduName}/pods': fetchMethod('GET/ecpapi/v2/sdus/{sduName}/pods'),

    /**
     * Interface name：GetSDUPod
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1391&itf=8794
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/sdus/{sduName}/pods/{podName}': fetchMethod('GET/ecpapi/v2/sdus/{sduName}/pods/{podName}'),

    /**
     * Interface name：ListDeploymentPods
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1391&itf=8795
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods': fetchMethod(
      'GET/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods'
    ),

    /**
     * Interface name：Kill Pod
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1391&itf=8796
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods/{podName}:kill': fetchMethod(
      'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods/{podName}:kill'
    ),

    /**
     * Interface name：GetPodsMetrics
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1391&itf=8797
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods:metrics': fetchMethod(
      'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods:metrics'
    ),

    /**
     * Interface name：GetSDUSummary
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1392&itf=8798
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/sdus/{sduName}/summary': fetchMethod('GET/ecpapi/v2/sdus/{sduName}/summary'),

    /**
     * Interface name：StopResourceBySdu
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1392&itf=8799
     * @param req request parameters
     * @param extra request config parameters
     */
    'POST/ecpapi/v2/sdus/{sduName}/svcdeploys:stop': fetchMethod('POST/ecpapi/v2/sdus/{sduName}/svcdeploys:stop'),

    /**
     * Interface name：ListAllSDUsSummary
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1392&itf=8800
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/services/sdus/summary': fetchMethod('GET/ecpapi/v2/services/sdus/summary'),

    /**
     * Interface name：ListServiceSDU
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1392&itf=8801
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/services/{serviceName}/sdus': fetchMethod('GET/ecpapi/v2/services/{serviceName}/sdus'),

    /**
     * Interface name：ListDeployZone
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1393&itf=8802
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/service/{serviceName}/deployzones': fetchMethod('GET/ecpapi/v2/service/{serviceName}/deployzones'),

    /**
     * Interface name：QueryECPTree
     * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1394&itf=8803
     * @param req request parameters
     * @param extra request config parameters
     */
    'GET/ecpapi/v2/tree/{rootType}/key/{rootKey}': fetchMethod('GET/ecpapi/v2/tree/{rootType}/key/{rootKey}'),
  }
}
