/* md5: 8b1ead165c687e79487db0a8af472b0f */
/* Rap repository id: 228 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=228
 */

/**
 * Interface name：listAllAZv1s
 * Rap url: https://rap.shopee.io/repository/editor?id=228&mod=1022&itf=11860
 */

import {IsNotEmpty, IsString, IsBoolean, ValidateNested, IsArray} from 'class-validator'
import {Type} from 'class-transformer'

export class Item492475 {
  @IsNotEmpty()
  @IsString({each: true})
  @IsArray()
  'azs': string[]
}

export class GetApisEnvsV2AzListNamesReqDto {}
export class GetApisEnvsV2AzListNamesResDto {
  @IsNotEmpty()
  @IsString()
  'version': string

  @IsNotEmpty()
  @IsBoolean()
  'success': boolean

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item492475)
  'result': Item492475
}
