/* md5: 9957ed119cf5f0f97ef3b0c736394734 */
/* Rap repository id: 228 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=228
 */

/**
 * Interface name：Get CID list
 * Rap url: https://rap.shopee.io/repository/editor?id=228&mod=1395&itf=8806
 */

import {IsNotEmpty, IsString, IsBoolean, ValidateNested, IsArray, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class Item168169 {
  @IsNotEmpty()
  @IsString({each: true})
  @IsArray()
  'alias_name': string[]

  @IsNotEmpty()
  @IsNumber()
  'enum_value': number

  @IsNotEmpty()
  @IsString({each: true})
  @IsArray()
  'name': string[]

  @IsNotEmpty()
  @IsBoolean()
  'visible': boolean
}

export class GetApisEnvsV2CidListReqDto {}
export class GetApisEnvsV2CidListResDto {
  @IsNotEmpty()
  @IsString()
  'version': string

  @IsNotEmpty()
  @IsBoolean()
  'success': boolean

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item168169)
  @IsArray()
  'result': Item168169[]
}
