/* md5: d68790f1d258dc2bb31056377965dbfd */
/* Rap repository id: 228 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=228
 */

/**
 * Interface name：Get ENV list
 * Rap url: https://rap.shopee.io/repository/editor?id=228&mod=1395&itf=8805
 */

import {IsNotEmpty, IsString, IsBoolean, ValidateNested, IsArray, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class Item168163 {
  @IsNotEmpty()
  @IsString({each: true})
  @IsArray()
  'alias_name': string[]

  @IsNotEmpty()
  @IsNumber()
  'enum_value': number

  @IsNotEmpty()
  @IsString({each: true})
  @IsArray()
  'name': string[]
}

export class GetApisEnvsV2EnvListReqDto {}
export class GetApisEnvsV2EnvListResDto {
  @IsNotEmpty()
  @IsString()
  'version': string

  @IsNotEmpty()
  @IsBoolean()
  'success': boolean

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item168163)
  @IsArray()
  'result': Item168163[]
}
