/* md5: 20a5db6fa49e70a6a6cb4c08c145deb3 */
/* Rap repository id: 228 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=228
 */

export class ItemEmpty {}

export {GetApisEnvsV2EnvListReqDto, GetApisEnvsV2EnvListResDto} from './get-apis-envs-v2-env-list.dto'
export {GetApisEnvsV2CidListReqDto, GetApisEnvsV2CidListResDto} from './get-apis-envs-v2-cid-list.dto'
export {GetApisAzMetaV1AzQueryAzsReqDto, GetApisAzMetaV1AzQueryAzsResDto} from './get-apis-az_meta-v1-az-query_azs.dto'
export {GetApisEnvsV2AzListNamesReqDto, GetApisEnvsV2AzListNamesResDto} from './get-apis-envs-v2-az-list_names.dto'
