apiVersion: v1
kind: Service
metadata:
  labels:
    app: ske-kubernetes-node-gateway
  name: ske-kubernetes-node-gateway
  namespace: $NAMESPACE
spec:
  ports:
    - port: $POD_PORT
      targetPort: $POD_PORT
      name: web
    - port: $METRICS_PORT
      targetPort: $METRICS_PORT
      name: metrics
  selector:
    app: ske-kubernetes-node-gateway
