/* md5: 91b55bb1fd4dca2c0da6063e1d922372 */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

export const IReqType = {
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:cancelcanary': {sduName: 2, deployId: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:editresource': {sduName: 2, deployId: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:fullrelease': {sduName: 2, deployId: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:restart': {sduName: 2, deployId: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:rollback': {sduName: 2, deployId: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:stop': {sduName: 2, deployId: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}:suspend': {sduName: 2, deployId: 2},
  'POST/ecpapi/v2/services/{serviceName}/bulk_get_deployments': {serviceName: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods/{podName}:kill': {sduName: 2, deployId: 2, podName: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods/metrics': {deployId: 2, sduName: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods/{podName}/files': {sduName: 2, podName: 2, deployId: 2},
  'POST/ecpapi/v2/sdus/{sduName}/svcdeploys/{deployId}/pods/{podName}/file:read': {sduName: 2, podName: 2, deployId: 2},
  'DELETE/ecpapi/v2/pvpvc/{uuid}': {uuid: 2},
  'DELETE/ecpapi/v2/pvsecret/{uuid}': {uuid: 2},
}
