/* md5: 2bb5f47bd1293178f3e7226f54dad45c */
/* Rap repository id: 247 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=247
 */

export const IReqType = {}
