include:
  - project: 'shopee/sz-devops/dev-infra/model-x'
    ref: master
    file: '/templates/main.yml'

default:
  image: node:14

variables:
  YARN_CACHE_FOLDER: /etc/ci_cache/yarn_cache

stages:
  - ipg-dex #for security scan by Security Team
  - test
  - cr
  - publish-test
  - catch-error

eslint:
  stage: test
  script:
    - yarn --frozen-lockfile --cache-folder $YARN_CACHE_FOLDER
    - yarn lint
  only:
    - merge_requests
    - master
    - tags
    - /^release-.*$

tsc:
  stage: test
  script:
    - yarn --frozen-lockfile --cache-folder $YARN_CACHE_FOLDER
    - yarn check-type
  only:
    - merge_requests
    - master
    - tags
    - /^release-.*$

CR:
  stage: cr
  only:
    - merge_requests
  script:
    - yarn config set registry https://npm.shopee.io/
    - yarn global add @infra/code-review-helper
    - code-review-helper notifyAssignees

mr_status_notify:
  stage: test
  only:
    - triggers
  script:
    - yarn config set registry https://npm.shopee.io/
    - yarn global add @infra/code-review-helper
    # MR提交后2小时没有评论视为超时，开始MR后，超过半小时没新增评论视为MR完成
    - code-review-helper mergeRequestStatusNotifier true 120 30

mr_error_notify:
  stage: catch-error
  rules:
    - if: $CI_MERGE_REQUEST_IID # if是mr
      when: on_failure
  script:
    - yarn config set registry https://npm.shopee.io/
    - yarn global add @infra/code-review-helper
    - code-review-helper pipelineFailureNotification


PublishTest:
  stage: publish-test
  only:
    - test
  script:
    - yarn add got@^11.8.2
    - node deploy/publish-test.js

check:
  variables:
    SEA_TALK_ROBOT: "$NOTIFICATION_SEATALK_WEBHOOK"        # seatalk群组机器人的 webhook url， 机器人配置详见https://static.cdn.haiserve.com/seatalk/client/shared/notice_bot/guidelines.html
    SONAR_INCLUDE: "src/**"              # 用户自定义代码规范需要扫描的文件
    SEC_NO_ERROR: "true"    # 即使安全检测不通过也不期望job error
  extends: .model-x-check
  stage: ipg-dex #这里替换为源项目对应的stage名称
  only:
    - master
