/* md5: b1eb33e01cea6a8f363e48c7abe745ae */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：GetPodLogs
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=909&itf=10672
 */

import {IsNotEmpty, IsString, IsOptional, IsBoolean} from 'class-validator'

export class GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPods1PodNameLogsReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsString()
  'deployId': string

  @IsNotEmpty()
  @IsString()
  'podName': string

  @IsOptional()
  @IsBoolean()
  'isPrevious'?: boolean

  @IsOptional()
  @IsString()
  'namespace'?: string

  @IsOptional()
  @IsString()
  'cluster'?: string
}
export class GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPods1PodNameLogsResDto {
  @IsNotEmpty()
  @IsString()
  'data': string
}
