/* md5: a5674847115ca60c89caec169b62d877 */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：HealthCheck
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=904&itf=5314
 */

import {IsOptional, IsString} from 'class-validator'

export class GetEcpapiV2CheckReqDto {}
export class GetEcpapiV2CheckResDto {
  @IsOptional()
  @IsString()
  'app'?: string

  @IsOptional()
  @IsString()
  'message'?: string
}
