/* md5: 939995cd8f0289419689b22f0084b6d2 */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：ListDeloymentPods
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=909&itf=5333
 */

import {IsNotEmpty, IsString, ValidateNested, IsArray, IsNumber, IsBoolean} from 'class-validator'
import {Type} from 'class-transformer'

export class Item379369 {
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item379363)
  'terminated': Item379363
}

export class Item379363 {
  @IsNotEmpty()
  @IsString()
  'containerId': string

  @IsNotEmpty()
  @IsNumber()
  'exitCode': number

  @IsNotEmpty()
  @IsString()
  'message': string

  @IsNotEmpty()
  @IsString()
  'reason': string

  @IsNotEmpty()
  @IsNumber()
  'signal': number
}

export class Item379362 {
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item379363)
  'terminated': Item379363
}

export class Item379356 {
  @IsNotEmpty()
  @IsString()
  'containerId': string

  @IsNotEmpty()
  @IsString()
  'image': string

  @IsNotEmpty()
  @IsString()
  'imageId': string

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item379369)
  'lastState': Item379369

  @IsNotEmpty()
  @IsString()
  'name': string

  @IsNotEmpty()
  @IsBoolean()
  'ready': boolean

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item379362)
  'state': Item379362
}

export class Item379355 {
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item379356)
  @IsArray()
  'containerStatuses': Item379356[]
}

export class Item370885 {
  @IsNotEmpty()
  @IsString()
  'containerId': string

  @IsNotEmpty()
  @IsString()
  'containerName': string

  @IsNotEmpty()
  @IsString()
  'contianerName': string
}

export class Item99605 {
  @IsNotEmpty()
  @IsString()
  'cid': string

  @IsNotEmpty()
  @IsString()
  'clusterName': string

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item370885)
  @IsArray()
  'containerInfo': Item370885[]

  @IsNotEmpty()
  @IsNumber()
  'createdTime': number

  @IsNotEmpty()
  @IsString()
  'env': string

  @IsNotEmpty()
  @IsString()
  'idc': string

  @IsNotEmpty()
  @IsNumber()
  'lastRestartTime': number

  @IsNotEmpty()
  @IsString()
  'namespace': string

  @IsNotEmpty()
  @IsString()
  'nodeIp': string

  @IsNotEmpty()
  @IsString()
  'nodeName': string

  @IsNotEmpty()
  @IsString()
  'phase': string

  @IsNotEmpty()
  @IsString()
  'podIp': string

  @IsNotEmpty()
  @IsString()
  'podName': string

  @IsNotEmpty()
  @IsNumber()
  'podPort': number

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item379355)
  'podStatus': Item379355

  @IsNotEmpty()
  @IsNumber()
  'restartCount': number

  @IsNotEmpty()
  @IsString()
  'sdu': string

  @IsNotEmpty()
  @IsString()
  'status': string

  @IsNotEmpty()
  @IsString()
  'tag': string
}

export class GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPodsReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsString()
  'deployId': string
}
export class GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPodsResDto {
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item99605)
  @IsArray()
  'items': Item99605[]

  @IsNotEmpty()
  @IsNumber()
  'total': number
}
