/* md5: f5bd376cfa0edf44aec5b73717e67a0c */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：GetPVPVC
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=1847&itf=11421
 */

import {IsNotEmpty, IsString} from 'class-validator'

export class GetEcpapiV2Pvpvc1UuidReqDto {
  @IsNotEmpty()
  @IsString()
  'uuid': string
}
export class GetEcpapiV2Pvpvc1UuidResDto {
  @IsNotEmpty()
  @IsString()
  'id': string

  @IsNotEmpty()
  @IsString()
  'uuid': string

  @IsNotEmpty()
  @IsString()
  'name': string

  @IsNotEmpty()
  @IsString()
  'serviceId': string

  @IsNotEmpty()
  @IsString()
  'serviceName': string

  @IsNotEmpty()
  @IsString()
  'project': string

  @IsNotEmpty()
  @IsString()
  'module': string

  @IsNotEmpty()
  @IsString()
  'env': string

  @IsNotEmpty()
  @IsString()
  'cid': string

  @IsNotEmpty()
  @IsString()
  'az': string

  @IsNotEmpty()
  @IsString()
  'secret': string

  @IsNotEmpty()
  @IsString()
  'accessMode': string

  @IsNotEmpty()
  @IsString()
  'subpath': string

  @IsNotEmpty()
  @IsString()
  'status': string

  @IsNotEmpty()
  @IsString()
  'updatedAt': string
}
