/* md5: c651d3cae58dfb524dd1026146d1cc2c */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：GetPVSecret
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=1847&itf=11428
 */

import {IsNotEmpty, IsString} from 'class-validator'

export class GetEcpapiV2Pvsecret1UuidReqDto {
  @IsNotEmpty()
  @IsString()
  'uuid': string
}
export class GetEcpapiV2Pvsecret1UuidResDto {
  @IsNotEmpty()
  @IsString()
  'id': string

  @IsNotEmpty()
  @IsString()
  'serviceId': string

  @IsNotEmpty()
  @IsString()
  'serviceName': string

  @IsNotEmpty()
  @IsString()
  'uuid': string

  @IsNotEmpty()
  @IsString()
  'name': string

  @IsNotEmpty()
  @IsString()
  'project': string

  @IsNotEmpty()
  @IsString()
  'module': string

  @IsNotEmpty()
  @IsString()
  'env': string

  @IsNotEmpty()
  @IsString()
  'az': string

  @IsNotEmpty()
  @IsString()
  'ussAppid': string

  @IsNotEmpty()
  @IsString()
  'ussAppSecret': string

  @IsNotEmpty()
  @IsString()
  'intranetDomain': string

  @IsNotEmpty()
  @IsString()
  'updatedAt': string
}
