/* md5: ea54cdc506e6163ba6863048657869ab */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：ListNodes
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=905&itf=5317
 */

import {IsNotEmpty, IsString, ValidateNested, IsArray, IsOptional, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'
import {ItemEmpty} from '.'

export class Item99420 {
  @IsOptional()
  @IsNumber()
  'applied'?: number

  @IsOptional()
  @IsNumber()
  'used'?: number
}

export class Item99414 {
  @IsOptional()
  @IsString()
  'effect'?: string

  @IsOptional()
  @IsString()
  'key'?: string

  @IsOptional()
  @IsString()
  'val'?: string
}

export class Item99411 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item99420)
  'cpu'?: Item99420

  @IsOptional()
  @ValidateNested()
  @Type(() => Item99420)
  'mem'?: Item99420

  @IsOptional()
  @ValidateNested()
  @Type(() => Item99420)
  'pods'?: Item99420
}

export class Item99409 {
  @IsOptional()
  @IsString()
  'cluster'?: string

  @IsOptional()
  @IsArray()
  'extraStatus'?: any[]

  @IsOptional()
  @IsString()
  'ip'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => ItemEmpty)
  'labels'?: ItemEmpty

  @IsOptional()
  @ValidateNested()
  @Type(() => Item99411)
  'metrics'?: Item99411

  @IsOptional()
  @IsString()
  'nodeName'?: string

  @IsOptional()
  @IsArray()
  'roles'?: any[]

  @IsOptional()
  @IsString()
  'status'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item99414)
  @IsArray()
  'taints'?: Item99414[]
}

export class GetEcpapiV2Clusters1ClusterNameNodesReqDto {
  @IsNotEmpty()
  @IsString()
  'clusterName': string
}
export class GetEcpapiV2Clusters1ClusterNameNodesResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item99409)
  @IsArray()
  'items'?: Item99409[]

  @IsOptional()
  @IsNumber()
  'total'?: number
}
