/* md5: 33dca977d164d15d9683ce6109dced73 */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：ListAzDetail
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=903&itf=6132
 */

import {IsNotEmpty, IsString, ValidateNested, IsArray} from 'class-validator'
import {Type} from 'class-transformer'

export class Item113696 {
  @IsNotEmpty()
  @IsString({each: true})
  @IsArray()
  'capability': string[]

  @IsNotEmpty()
  @IsString({each: true})
  @IsArray()
  'clusters': string[]

  @IsNotEmpty()
  @IsString()
  'env': string

  @IsNotEmpty()
  @IsString()
  'name': string

  @IsNotEmpty()
  @IsString()
  'version': string
}

export class GetEcpapiV2AzsReqDto {
  @IsNotEmpty()
  @IsString()
  'env': string
}
export class GetEcpapiV2AzsResDto {
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item113696)
  @IsArray()
  'items': Item113696[]
}
