/* md5: 49175f7caa0a2a9ae2f4e5504042e461 */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：ListAllZones
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=1200&itf=7358
 */

import {IsNotEmpty, IsString, ValidateNested, IsArray, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class Item143330 {
  @IsNotEmpty()
  @IsString()
  'az': string

  @IsNotEmpty()
  @IsString()
  'description': string

  @IsNotEmpty()
  @IsString()
  'zoneName': string
}

export class GetEcpapiV2Service1ServiceNameDeployzonesReqDto {
  @IsNotEmpty()
  @IsString()
  'serviceName': string
}
export class GetEcpapiV2Service1ServiceNameDeployzonesResDto {
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item143330)
  @IsArray()
  'items': Item143330[]

  @IsNotEmpty()
  @IsNumber()
  'totalSize': number
}
