/* md5: 5060d00a32f4858eac99c98b2a955411 */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：GetPodLogs
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=909&itf=10672
 */

import {IsNotEmpty, IsString, IsOptional} from 'class-validator'

export class GetEcpapiV2Sdu1SduNameSvcdeploys1DeployIdPods1PodNameLogsReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsString()
  'deployId': string

  @IsNotEmpty()
  @IsString()
  'podName': string

  @IsOptional()
  @IsString()
  'containerName'?: string

  @IsOptional()
  @IsString()
  'containerId'?: string

  @IsOptional()
  @IsString()
  'hostIp'?: string

  @IsOptional()
  @IsString()
  'clusterName'?: string

  @IsOptional()
  @IsString()
  'env'?: string
}
export class GetEcpapiV2Sdu1SduNameSvcdeploys1DeployIdPods1PodNameLogsResDto {
  @IsNotEmpty()
  @IsString()
  'data': string
}
