/* md5: 96d6b40a2e08682240f1f2a873005b7e */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：GetSDUSummary
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=908&itf=5331
 */

import {IsNotEmpty, IsString, ValidateNested, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class Item99569 {
  @IsNotEmpty()
  @IsNumber()
  'canaryInstances': number

  @IsNotEmpty()
  @IsNumber()
  'cpu': number

  @IsNotEmpty()
  @IsNumber()
  'disk': number

  @IsNotEmpty()
  @IsNumber()
  'healthyInstances': number

  @IsNotEmpty()
  @IsNumber()
  'killingInstances': number

  @IsNotEmpty()
  @IsNumber()
  'lastDeployed': number

  @IsNotEmpty()
  @IsNumber()
  'mem': number

  @IsNotEmpty()
  @IsNumber()
  'releaseInstances': number

  @IsNotEmpty()
  @IsNumber()
  'runningInstances': number

  @IsNotEmpty()
  @IsNumber()
  'stagingInstances': number

  @IsNotEmpty()
  @IsNumber()
  'startingInstances': number

  @IsNotEmpty()
  @IsString()
  'state': string

  @IsNotEmpty()
  @IsNumber()
  'targetInstances': number

  @IsNotEmpty()
  @IsNumber()
  'unhealthyInstances': number

  @IsNotEmpty()
  @IsNumber()
  'unknownInstances': number
}

export class GetEcpapiV2Sdus1SduNameSummaryReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string
}
export class GetEcpapiV2Sdus1SduNameSummaryResDto {
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item99569)
  'summary': Item99569
}
