/* md5: 0a8f99eb72b791bbae896db6e4d39c03 */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：QueryClusterDetail
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=905&itf=5315
 */

import {IsNotEmpty, IsString, ValidateNested, IsOptional, IsBoolean} from 'class-validator'
import {Type} from 'class-transformer'

export class Item99385 {
  @IsOptional()
  @IsString()
  'azV1'?: string

  @IsOptional()
  @IsString()
  'azV2'?: string

  @IsOptional()
  @IsString()
  'clusterKey'?: string

  @IsOptional()
  @IsString()
  'displayName'?: string

  @IsOptional()
  @IsString()
  'ecpVersion'?: string

  @IsOptional()
  @IsBoolean()
  'handleByGalio'?: boolean

  @IsOptional()
  @IsString()
  'kubeApiserverType'?: string

  @IsOptional()
  @IsString()
  'kubeConfig'?: string

  @IsOptional()
  @IsString()
  'monitoringUrl'?: string

  @IsOptional()
  @IsString()
  'region'?: string

  @IsOptional()
  @IsString()
  'segment'?: string

  @IsOptional()
  @IsString()
  'uuid'?: string
}

export class Item99384 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item99385)
  'meta'?: Item99385
}

export class GetEcpapiV2Cluster1UuidDetailReqDto {
  @IsNotEmpty()
  @IsString()
  'uuid': string
}
export class GetEcpapiV2Cluster1UuidDetailResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item99384)
  'detail'?: Item99384
}
