/* md5: 1e48a9e3d3fd35edb494feaa7f838e57 */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：ping
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=819&itf=4790
 */

import {IsOptional, IsString, IsNumber, IsBoolean, ValidateNested, IsArray} from 'class-validator'
import {Type} from 'class-transformer'

export class Item81888 {
  /**
    example array element attribute
  */
  @IsOptional()
  @IsString()
  'bar'?: string

  /**
    example array element attribute
  */
  @IsOptional()
  @IsNumber()
  'foo'?: number
}

export class GetApiV1PingReqDto {}
export class GetApiV1PingResDto {
  /**
    example string attribute
  */
  @IsOptional()
  @IsString()
  'string'?: string

  /**
    example number attribute
  */
  @IsOptional()
  @IsNumber()
  'number'?: number

  /**
    example boolean attribute
  */
  @IsOptional()
  @IsBoolean()
  'boolean'?: boolean

  /**
    example regexp attribute
  */
  @IsOptional()
  @IsString()
  'regexp'?: string

  /**
    example function attribute
  */
  @IsOptional()
  @IsString()
  'function'?: string

  /**
    example array attribute
  */
  @IsOptional()
  @ValidateNested()
  @Type(() => Item81888)
  @IsArray()
  'array'?: Item81888[]

  /**
    example customized array element attribute
  */
  @IsOptional()
  @IsArray()
  'items'?: any[]

  /**
    example object attribute
  */
  @IsOptional()
  @ValidateNested()
  @Type(() => Item81888)
  'object'?: Item81888

  /**
    example placeholder
  */
  @IsOptional()
  @IsString()
  'placeholder'?: string
}
