/* md5: a09b773ddc7c0ad55d91b517c7b7c224 */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：ListPVPVC
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=1847&itf=11423
 */

import {IsNotEmpty, IsString, ValidateNested, IsArray} from 'class-validator'
import {Type} from 'class-transformer'

export class Item456238 {
  @IsNotEmpty()
  @IsString()
  'accessMode': string

  @IsNotEmpty()
  @IsString()
  'az': string

  @IsNotEmpty()
  @IsString()
  'cid': string

  @IsNotEmpty()
  @IsString()
  'env': string

  @IsNotEmpty()
  @IsString()
  'id': string

  @IsNotEmpty()
  @IsString()
  'module': string

  @IsNotEmpty()
  @IsString()
  'name': string

  @IsNotEmpty()
  @IsString()
  'project': string

  @IsNotEmpty()
  @IsString()
  'secret': string

  @IsNotEmpty()
  @IsString()
  'serviceId': string

  @IsNotEmpty()
  @IsString()
  'serviceName': string

  @IsNotEmpty()
  @IsString()
  'status': string

  @IsNotEmpty()
  @IsString()
  'subpath': string

  @IsNotEmpty()
  @IsString()
  'updatedAt': string

  @IsNotEmpty()
  @IsString()
  'uuid': string
}

export class GetEcpapiV2Pvpvcs1ServiceIdReqDto {
  @IsNotEmpty()
  @IsString()
  'serviceId': string
}
export class GetEcpapiV2Pvpvcs1ServiceIdResDto {
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item456238)
  @IsArray()
  'pvPvc': Item456238[]
}
