/* md5: e8f524241855116cc3c35c31216f8497 */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：bulk get sdus
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=908&itf=11357
 */

import {IsNotEmpty, IsString, IsOptional, IsBoolean, ValidateNested, IsArray, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class Item440354 {
  @IsNotEmpty()
  @IsNumber()
  'canaryInstances': number

  @IsNotEmpty()
  @IsNumber()
  'cpu': number

  @IsNotEmpty()
  @IsNumber()
  'disk': number

  @IsNotEmpty()
  @IsNumber()
  'healthyInstances': number

  @IsNotEmpty()
  @IsNumber()
  'killingInstances': number

  @IsNotEmpty()
  @IsNumber()
  'lastDeployed': number

  @IsNotEmpty()
  @IsNumber()
  'mem': number

  @IsNotEmpty()
  @IsNumber()
  'releaseInstances': number

  @IsNotEmpty()
  @IsNumber()
  'runningInstances': number

  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsNumber()
  'stagingInstances': number

  @IsNotEmpty()
  @IsNumber()
  'startingInstances': number

  @IsNotEmpty()
  @IsString()
  'state': string

  @IsNotEmpty()
  @IsNumber()
  'targetInstances': number

  @IsNotEmpty()
  @IsNumber()
  'unhealthyInstances': number

  @IsNotEmpty()
  @IsNumber()
  'unknownInstances': number
}

export class Item440350 {
  @IsNotEmpty()
  @IsString()
  'module': string

  @IsNotEmpty()
  @IsString()
  'project': string
}

export class Item440340 {
  @IsNotEmpty()
  @IsString()
  'cid': string

  @IsNotEmpty()
  @IsString()
  'deploymentLink': string

  @IsNotEmpty()
  @IsString()
  'env': string

  @IsNotEmpty()
  @IsString({each: true})
  @IsArray()
  'idcs': string[]

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item440350)
  'identifier': Item440350

  @IsNotEmpty()
  @IsString()
  'resourceType': string

  @IsNotEmpty()
  @IsString()
  'sdu': string

  @IsNotEmpty()
  @IsNumber()
  'sduId': number

  @IsNotEmpty()
  @IsNumber()
  'serviceId': number

  @IsNotEmpty()
  @IsString()
  'serviceName': string

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item440354)
  'summary': Item440354

  @IsNotEmpty()
  @IsString()
  'version': string
}

export class GetEcpapiV2Services1ServiceNameBulkGetSdusReqDto {
  @IsNotEmpty()
  @IsString()
  'serviceName': string

  @IsOptional()
  @IsString()
  'filterBy'?: string

  @IsOptional()
  @IsString()
  'keyword'?: string

  @IsOptional()
  @IsBoolean()
  'isGroup'?: boolean
}
export class GetEcpapiV2Services1ServiceNameBulkGetSdusResDto {
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item440340)
  @IsArray()
  'items': Item440340[]

  @IsNotEmpty()
  @IsNumber()
  'totalSize': number
}
