/* md5: 3ec4115ebc46b706dd9ff34bfafc5199 */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：ListWorkload
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=906&itf=6172
 */

import {IsNotEmpty, IsString, ValidateNested, IsArray} from 'class-validator'
import {Type} from 'class-transformer'

export class Item115134 {
  @IsNotEmpty()
  @IsString()
  'category': string

  @IsNotEmpty()
  @IsString()
  'name': string

  @IsNotEmpty()
  @IsString()
  'nameDisplay': string

  @IsNotEmpty()
  @IsString({each: true})
  @IsArray()
  'orchestrators': string[]

  @IsNotEmpty()
  @IsString()
  'type': string
}

export class Item115131 {
  @IsNotEmpty()
  @IsString()
  'az': string

  @IsNotEmpty()
  @IsString()
  'env': string

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item115134)
  @IsArray()
  'workloads': Item115134[]
}

export class GetEcpapiV2WorkloadsReqDto {
  @IsNotEmpty()
  @IsString()
  'env': string
}
export class GetEcpapiV2WorkloadsResDto {
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item115131)
  @IsArray()
  'items': Item115131[]
}
