/* md5: c041da423216bcfbebf36551bd8633cb */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

export class ItemEmpty {}

export {GetApiV1PingReqDto, GetApiV1PingResDto} from './get-api-v1-ping.dto'
export {
  GetEcpapiV2Az1AzKeyMappingReqDto,
  GetEcpapiV2Az1AzKeyMappingResDto,
} from './get-ecpapi-v2-az-{azKey}-mapping.dto'
export {GetEcpapiV2AzsReqDto, GetEcpapiV2AzsResDto} from './get-ecpapi-v2-azs.dto'
export {GetEcpapiV2CheckReqDto, GetEcpapiV2CheckResDto} from './get-ecpapi-v2-check.dto'
export {
  GetEcpapiV2Cluster1UuidDetailReqDto,
  GetEcpapiV2Cluster1UuidDetailResDto,
} from './get-ecpapi-v2-cluster-{uuid}-detail.dto'
export {PostEcpapiV2ClustermetaReqDto, PostEcpapiV2ClustermetaResDto} from './post-ecpapi-v2-clustermeta.dto'
export {
  GetEcpapiV2Clusters1ClusterNameNodesReqDto,
  GetEcpapiV2Clusters1ClusterNameNodesResDto,
} from './get-ecpapi-v2-clusters-{clusterName}-nodes.dto'
export {
  PostEcpapiV2Sdus1SduNameDeploymentsReqDto,
  PostEcpapiV2Sdus1SduNameDeploymentsResDto,
} from './post-ecpapi-v2-sdus-{sduName}-deployments.dto'
export {
  GetEcpapiV2Sdus1SduNameSvcdeploysReqDto,
  GetEcpapiV2Sdus1SduNameSvcdeploysResDto,
} from './get-ecpapi-v2-sdus-{sduName}-svcdeploys.dto'
export {
  GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdMetaReqDto,
  GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdMetaResDto,
} from './get-ecpapi-v2-sdus-{sduName}-svcdeploys-{deployId}-meta.dto'
export {
  GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdResultReqDto,
  GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdResultResDto,
} from './get-ecpapi-v2-sdus-{sduName}-svcdeploys-{deployId}-result.dto'
export {
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdCancelcanaryReqDto,
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdCancelcanaryResDto,
} from './post-ecpapi-v2-sdus-{sduName}-svcdeploys-{deployId}:cancelcanary.dto'
export {
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdEditresourceReqDto,
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdEditresourceResDto,
} from './post-ecpapi-v2-sdus-{sduName}-svcdeploys-{deployId}:editresource.dto'
export {
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdFullreleaseReqDto,
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdFullreleaseResDto,
} from './post-ecpapi-v2-sdus-{sduName}-svcdeploys-{deployId}:fullrelease.dto'
export {
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdRestartReqDto,
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdRestartResDto,
} from './post-ecpapi-v2-sdus-{sduName}-svcdeploys-{deployId}:restart.dto'
export {
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdRollbackReqDto,
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdRollbackResDto,
} from './post-ecpapi-v2-sdus-{sduName}-svcdeploys-{deployId}:rollback.dto'
export {
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdScaleReqDto,
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdScaleResDto,
} from './post-ecpapi-v2-sdus-{sduName}-svcdeploys-{deployId}:scale.dto'
export {
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdStopReqDto,
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdStopResDto,
} from './post-ecpapi-v2-sdus-{sduName}-svcdeploys-{deployId}:stop.dto'
export {
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdSuspendReqDto,
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdSuspendResDto,
} from './post-ecpapi-v2-sdus-{sduName}-svcdeploys-{deployId}:suspend.dto'
export {GetEcpapiV2WorkloadsReqDto, GetEcpapiV2WorkloadsResDto} from './get-ecpapi-v2-workloads.dto'
export {
  GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdDeployHistoryReqDto,
  GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdDeployHistoryResDto,
} from './get-ecpapi-v2-sdus-{sduName}-svcdeploys-{deployId}-deploy_history.dto'
export {
  GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdDeployPreviewReqDto,
  GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdDeployPreviewResDto,
} from './get-ecpapi-v2-sdus-{sduName}-svcdeploys-{deployId}-deploy_preview.dto'
export {
  GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdEventsReqDto,
  GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdEventsResDto,
} from './get-ecpapi-v2-sdus-{sduName}-svcdeploys-{deployId}-events.dto'
export {
  PostEcpapiV2Services1ServiceNameBulkGetDeploymentsReqDto,
  PostEcpapiV2Services1ServiceNameBulkGetDeploymentsResDto,
} from './post-ecpapi-v2-services-{serviceName}-bulk_get_deployments.dto'
export {
  GetEcpapiV2Sdus1SduNameHpasReqDto,
  GetEcpapiV2Sdus1SduNameHpasResDto,
} from './get-ecpapi-v2-sdus-{sduName}-hpas.dto'
export {
  GetEcpapiV2Sdus1SduNameSummaryReqDto,
  GetEcpapiV2Sdus1SduNameSummaryResDto,
} from './get-ecpapi-v2-sdus-{sduName}-summary.dto'
export {
  GetEcpapiV2Services1ServiceNameSdusReqDto,
  GetEcpapiV2Services1ServiceNameSdusResDto,
} from './get-ecpapi-v2-services-{serviceName}-sdus.dto'
export {
  GetEcpapiV2Services1ServiceNameBulkGetSdusReqDto,
  GetEcpapiV2Services1ServiceNameBulkGetSdusResDto,
} from './get-ecpapi-v2-services-{serviceName}-bulk_get_sdus.dto'
export {
  GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPodsReqDto,
  GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPodsResDto,
} from './get-ecpapi-v2-sdus-{sduName}-svcdeploys-{deployId}-pods.dto'
export {
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPods1PodNameKillReqDto,
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPods1PodNameKillResDto,
} from './post-ecpapi-v2-sdus-{sduName}-svcdeploys-{deployId}-pods-{podName}:kill.dto'
export {
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPodsMetricsReqDto,
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPodsMetricsResDto,
} from './post-ecpapi-v2-sdus-{sduName}-svcdeploys-{deployId}-pods-metrics.dto'
export {
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPods1PodNameFilesReqDto,
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPods1PodNameFilesResDto,
} from './post-ecpapi-v2-sdus-{sduName}-svcdeploys-{deployId}-pods-{podName}-files.dto'
export {
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPods1PodNameFileReadReqDto,
  PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPods1PodNameFileReadResDto,
} from './post-ecpapi-v2-sdus-{sduName}-svcdeploys-{deployId}-pods-{podName}-file:read.dto'
export {
  GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPods1PodNameLogsReqDto,
  GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPods1PodNameLogsResDto,
} from './get-ecpapi-v2-sdus-{sduName}-svcdeploys-{deployId}-pods-{podName}-logs.dto'
export {
  GetEcpapiV2Service1ServiceNameDeployzonesReqDto,
  GetEcpapiV2Service1ServiceNameDeployzonesResDto,
} from './get-ecpapi-v2-service-{serviceName}-deployzones.dto'
export {GetEcpapiV2Pvpvc1UuidReqDto, GetEcpapiV2Pvpvc1UuidResDto} from './get-ecpapi-v2-pvpvc-{uuid}.dto'
export {PostEcpapiV2PvpvcsReqDto, PostEcpapiV2PvpvcsResDto} from './post-ecpapi-v2-pvpvcs.dto'
export {
  GetEcpapiV2Pvpvcs1ServiceIdReqDto,
  GetEcpapiV2Pvpvcs1ServiceIdResDto,
} from './get-ecpapi-v2-pvpvcs-{serviceId}.dto'
export {DeleteEcpapiV2Pvpvc1UuidReqDto, DeleteEcpapiV2Pvpvc1UuidResDto} from './delete-ecpapi-v2-pvpvc-{uuid}.dto'
export {PostEcpapiV2PvsecretReqDto, PostEcpapiV2PvsecretResDto} from './post-ecpapi-v2-pvsecret.dto'
export {PutEcpapiV2PvsecretReqDto, PutEcpapiV2PvsecretResDto} from './put-ecpapi-v2-pvsecret.dto'
export {GetEcpapiV2Pvsecret1UuidReqDto, GetEcpapiV2Pvsecret1UuidResDto} from './get-ecpapi-v2-pvsecret-{uuid}.dto'
export {
  DeleteEcpapiV2Pvsecret1UuidReqDto,
  DeleteEcpapiV2Pvsecret1UuidResDto,
} from './delete-ecpapi-v2-pvsecret-{uuid}.dto'
export {
  GetEcpapiV2Pvsecrets1ServiceIdReqDto,
  GetEcpapiV2Pvsecrets1ServiceIdResDto,
} from './get-ecpapi-v2-pvsecrets-{serviceId}.dto'
export {
  PostEcpapiV2PvsecretIsexistReqDto,
  PostEcpapiV2PvsecretIsexistResDto,
} from './post-ecpapi-v2-pvsecret-isexist.dto'
export {PostEcpapiV2PvpvcReqDto, PostEcpapiV2PvpvcResDto} from './post-ecpapi-v2-pvpvc.dto'
