/* md5: 5c8d3ed2243e9949de4147c546f896d1 */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：GetLogFileContent
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=909&itf=10562
 */

import {IsNotEmpty, IsString, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPods1PodNameFileReadReqDto {
  @IsNotEmpty()
  @IsString()
  'read': string

  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsString()
  'podName': string

  @IsNotEmpty()
  @IsString()
  'hostIp': string

  @IsNotEmpty()
  @IsNumber()
  'offset': number

  @IsNotEmpty()
  @IsString()
  'path': string

  @IsNotEmpty()
  @IsNumber()
  'length': number

  @IsNotEmpty()
  @IsString()
  'deployId': string
}
export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPods1PodNameFileReadResDto {
  @IsNotEmpty()
  @IsString()
  'fileContent': string
}
