/* md5: a72f1a62813803ec568f0408d3665408 */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：RollbackDeployment
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=906&itf=5326
 */

import {IsNotEmpty, IsString, ValidateNested, IsArray, IsOptional} from 'class-validator'
import {Type} from 'class-transformer'

export class Item143438 {
  @IsNotEmpty()
  @IsString()
  'image': string

  @IsNotEmpty()
  @IsString()
  'name': string

  @IsNotEmpty()
  @IsString()
  'phase': string

  @IsNotEmpty()
  @IsString()
  'tag': string
}

export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdRollbackReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsString()
  'deployId': string

  @IsNotEmpty()
  @IsString()
  'deploymentId': string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item143438)
  @IsArray()
  'containers'?: Item143438[]
}
export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdRollbackResDto {}
