/* md5: 56ca68b499cfd41190eae60a18e1cf5f */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：GetPodsMetrics
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=909&itf=5335
 */

import {IsNotEmpty, IsString, ValidateNested, IsArray, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class Item107360 {
  @IsNotEmpty()
  @IsString()
  'namespace': string

  @IsNotEmpty()
  @IsString()
  'podName': string
}

export class Item99624 {
  @IsNotEmpty()
  @IsNumber()
  'applied': number

  @IsNotEmpty()
  @IsNumber()
  'used': number
}

export class Item99622 {
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item99624)
  'cpu': Item99624

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item99624)
  'memory': Item99624

  @IsNotEmpty()
  @IsString()
  'namespace': string

  @IsNotEmpty()
  @IsString()
  'podName': string
}

export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPodsMetricsReqDto {
  @IsNotEmpty()
  @IsString()
  'metrics': string

  @IsNotEmpty()
  @IsString()
  'deployId': string

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item107360)
  @IsArray()
  'pods': Item107360[]

  @IsNotEmpty()
  @IsString()
  'sduName': string
}
export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPodsMetricsResDto {
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item99622)
  @IsArray()
  'items': Item99622[]
}
