/* md5: 789a5b04666c04774faa910c3d38a70d */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：ListPodLogFiles
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=909&itf=10561
 */

import {IsNotEmpty, IsString, ValidateNested, IsArray, IsBoolean, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class Item375708 {
  @IsNotEmpty()
  @IsString()
  'gid': string

  @IsNotEmpty()
  @IsString()
  'groupName': string

  @IsNotEmpty()
  @IsBoolean()
  'isDir': boolean

  @IsNotEmpty()
  @IsNumber()
  'mod': number

  @IsNotEmpty()
  @IsString()
  'modStr': string

  @IsNotEmpty()
  @IsString()
  'modTime': string

  @IsNotEmpty()
  @IsString()
  'name': string

  @IsNotEmpty()
  @IsString()
  'path': string

  @IsNotEmpty()
  @IsString()
  'size': string

  @IsNotEmpty()
  @IsNumber()
  'uid': number

  @IsNotEmpty()
  @IsString()
  'userName': string
}

export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPods1PodNameFilesReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsString()
  'podName': string

  @IsNotEmpty()
  @IsString()
  'hostIp': string

  @IsNotEmpty()
  @IsString()
  'deployId': string
}
export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPods1PodNameFilesResDto {
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => Item375708)
  @IsArray()
  'files': Item375708[]
}
