/* md5: 5dfd39949e5057cabadfd6b8527066c5 */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：Kill Pod
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=909&itf=5334
 */

import {IsNotEmpty, IsString} from 'class-validator'

export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPods1PodNameKillReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsString()
  'deployId': string

  @IsNotEmpty()
  @IsString()
  'podName': string

  @IsNotEmpty()
  @IsString()
  'clusterName': string

  @IsNotEmpty()
  @IsString()
  'namespace': string
}
export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPods1PodNameKillResDto {}
