/* md5: 29f52220061ff801ea256a9f591258ad */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：ScaleDeployment
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=906&itf=5327
 */

import {IsNotEmpty, IsString, IsOptional, IsNumber, IsBoolean} from 'class-validator'
import {Type} from 'class-transformer'

export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdScaleReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsString()
  'deployId': string

  @IsOptional()
  @IsNumber()
  'releaseReplicas'?: number

  @IsOptional()
  @IsNumber()
  'canaryReplicas'?: number

  @IsOptional()
  @IsBoolean()
  'canaryValid'?: boolean
}
export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdScaleResDto {}
