/* md5: 8778c75b6e3bd652ecd019affc00442c */
/* Rap repository id: 185 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: http://rap.shopee.io/repository/editor?id=185
 */

/**
 * Interface name：CreateDeployment
 * Rap url: http://rap.shopee.io/repository/editor?id=185&mod=906&itf=5318
 */

import {IsNotEmpty, IsString, IsOptional} from 'class-validator'

export class PostEcpapiV2Sdus1SduNameDeploymentsReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string
}
export class PostEcpapiV2Sdus1SduNameDeploymentsResDto {
  @IsOptional()
  @IsString()
  'deployId'?: string
}
