/* md5: 47fabdc6951110b7801741f136034ecc */
/* Rap repository id: 211 */
/* Rapper version: 2.1.13 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=211
 */

export const IReqType = {}
