/* md5: f305566ca946d4733ffcad94b59f25ab */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：RemoveAppClusterConfig
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8766
 */

import {IsNotEmpty, IsString} from 'class-validator'

export class DeleteEcpapiV2Appclusterconfig1IdReqDto {
  @IsNotEmpty()
  @IsString()
  'id': string
}
export class DeleteEcpapiV2Appclusterconfig1IdResDto {}
