/* md5: 590b98a371d061647b194a898e6cb9c1 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：ListServiceDeployments
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8776
 */

import {IsNotEmpty, IsString, IsOptional, IsBoolean, ValidateNested, IsArray, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class Item193291 {
  @IsOptional()
  @IsString()
  'image'?: string

  @IsOptional()
  @IsString()
  'name'?: string

  @IsOptional()
  @IsString()
  'phase'?: string

  @IsOptional()
  @IsString()
  'tag'?: string

  @IsOptional()
  @IsString()
  'timestamp'?: string
}

export class Item193264 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193291)
  @IsArray()
  'containers'?: Item193291[]

  @IsOptional()
  @IsString()
  'orchestrator'?: string

  @IsOptional()
  @IsString()
  'reason'?: string
}

export class Item193263 {
  @IsOptional()
  @IsNumber()
  'canaryInstances'?: number

  @IsOptional()
  @IsNumber()
  'cpu'?: number

  @IsOptional()
  @IsNumber()
  'disk'?: number

  @IsOptional()
  @IsNumber()
  'healthyInstances'?: number

  @IsOptional()
  @IsNumber()
  'killingInstances'?: number

  @IsOptional()
  @IsNumber()
  'lastDeployed'?: number

  @IsOptional()
  @IsNumber()
  'mem'?: number

  @IsOptional()
  @IsNumber()
  'releaseInstances'?: number

  @IsOptional()
  @IsNumber()
  'runningInstances'?: number

  @IsOptional()
  @IsString()
  'sduName'?: string

  @IsOptional()
  @IsNumber()
  'stagingInstances'?: number

  @IsOptional()
  @IsNumber()
  'startingInstances'?: number

  @IsOptional()
  @IsString()
  'state'?: string

  @IsOptional()
  @IsNumber()
  'targetInstances'?: number

  @IsOptional()
  @IsNumber()
  'unhealthyInstances'?: number

  @IsOptional()
  @IsNumber()
  'unknownInstances'?: number
}

export class Item193256 {
  @IsOptional()
  @IsString()
  'azV1'?: string

  @IsOptional()
  @IsString()
  'azV2'?: string

  @IsOptional()
  @IsString()
  'bundle'?: string

  @IsOptional()
  @IsString()
  'cid'?: string

  @IsOptional()
  @IsString()
  'cluster'?: string

  @IsOptional()
  @IsString()
  'clusterType'?: string

  @IsOptional()
  @IsString()
  'componentType'?: string

  @IsOptional()
  @IsString()
  'deployEngine'?: string

  @IsOptional()
  @IsString()
  'deployId'?: string

  @IsOptional()
  @IsString()
  'env'?: string

  @IsOptional()
  @IsString()
  'feature'?: string

  @IsOptional()
  @IsString()
  'module'?: string

  @IsOptional()
  @IsString()
  'project'?: string

  @IsOptional()
  @IsString()
  'sduName'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193264)
  'status'?: Item193264

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193263)
  'summary'?: Item193263
}

export class GetEcpapiV2Sdus1SduNameSvcdeploysReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsOptional()
  @IsBoolean()
  'withdetail'?: boolean
}
export class GetEcpapiV2Sdus1SduNameSvcdeploysResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193256)
  @IsArray()
  'items'?: Item193256[]

  @IsOptional()
  @IsNumber()
  'total'?: number
}
