/* md5: 98b5395516d3c6a71e5eaac2cf5d4110 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：QueryECPTree
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1394&itf=8803
 */

import {IsNotEmpty, IsString, IsOptional, ValidateNested, IsArray} from 'class-validator'
import {Type} from 'class-transformer'

export class Item193605 {
  @IsOptional()
  @IsString({each: true})
  @IsArray()
  'leafKey'?: string[]

  @IsOptional()
  @IsString()
  'leafType'?: string

  @IsOptional()
  @IsString()
  'rootKey'?: string

  @IsOptional()
  @IsString()
  'rootType'?: string
}

export class GetEcpapiV2Tree1RootTypeKey1RootKeyReqDto {
  /**
    cmdb_tenant_id,project
  */
  @IsNotEmpty()
  @IsString()
  'rootType': string

  /**
    for cmdb_tenant, use cmdb_tenant_id
  */
  @IsNotEmpty()
  @IsString()
  'rootKey': string

  /**
    project,application
  */
  @IsOptional()
  @IsString()
  'leafType'?: string
}
export class GetEcpapiV2Tree1RootTypeKey1RootKeyResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193605)
  'tree'?: Item193605
}
