/* md5: abc6a56339bcd4231d43a85f902099b5 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：GetDeploymentHistory
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8781
 */

import {IsNotEmpty, IsString, ValidateNested, IsArray, IsOptional, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class Item167989 {
  @IsOptional()
  @IsArray()
  'containers'?: any[]

  @IsOptional()
  @IsString()
  'deploymentId'?: string

  @IsOptional()
  @IsNumber()
  'lastDeployed'?: number

  @IsOptional()
  @IsString()
  'state'?: string
}

export class GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdDeploymentHistoryReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsString()
  'deployId': string
}
export class GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdDeploymentHistoryResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item167989)
  @IsArray()
  'list'?: Item167989[]
}
