/* md5: d9bef55e2d5c2bf0313f68a171666f6c */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：QueryAZMapping
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1386&itf=8773
 */

import {IsNotEmpty, IsString, IsOptional, ValidateNested, IsArray} from 'class-validator'
import {Type} from 'class-transformer'

export class Item193231 {
  @IsOptional()
  @IsString()
  'azKey'?: string

  @IsOptional()
  @IsString()
  'version'?: string
}

export class GetEcpapiV2Azs1AzKeyMappingReqDto {
  @IsNotEmpty()
  @IsString()
  'azKey': string
}
export class GetEcpapiV2Azs1AzKeyMappingResDto {
  @IsOptional()
  @IsString()
  'version'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193231)
  @IsArray()
  'items'?: Item193231[]
}
