/* md5: 504d2f2607ead2d30db50fd518dde974 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：ListDeploymentPods
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1391&itf=8795
 */

import {IsNotEmpty, IsString, ValidateNested, IsArray, IsOptional, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class Item193504 {
  @IsOptional()
  @IsString()
  'containerId'?: string

  @IsOptional()
  @IsString()
  'contianerName'?: string
}

export class Item193495 {
  @IsOptional()
  @IsString()
  'cid'?: string

  @IsOptional()
  @IsString()
  'clusterName'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193504)
  @IsArray()
  'containerInfo'?: Item193504[]

  @IsOptional()
  @IsNumber()
  'createdTime'?: number

  @IsOptional()
  @IsString()
  'env'?: string

  @IsOptional()
  @IsString()
  'idc'?: string

  @IsOptional()
  @IsNumber()
  'lastRestartTime'?: number

  @IsOptional()
  @IsString()
  'namespace'?: string

  @IsOptional()
  @IsString()
  'nodeIp'?: string

  @IsOptional()
  @IsString()
  'nodeName'?: string

  @IsOptional()
  @IsString()
  'phase'?: string

  @IsOptional()
  @IsString()
  'podIp'?: string

  @IsOptional()
  @IsString()
  'podName'?: string

  @IsOptional()
  @IsNumber()
  'podPort'?: number

  @IsOptional()
  @IsNumber()
  'restartCount'?: number

  @IsOptional()
  @IsString()
  'sdu'?: string

  @IsOptional()
  @IsString()
  'status'?: string

  @IsOptional()
  @IsString()
  'tag'?: string
}

export class GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPodsReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsString()
  'deployId': string
}
export class GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPodsResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193495)
  @IsArray()
  'items'?: Item193495[]

  @IsOptional()
  @IsNumber()
  'total'?: number
}
