/* md5: 5dd0f06f90b0893f0ab4662471bf1b69 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：ListSDUHpasRequest
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1390&itf=8792
 */

import {IsNotEmpty, IsString, ValidateNested, IsArray, IsOptional, IsNumber, IsBoolean} from 'class-validator'
import {Type} from 'class-transformer'
import {ItemEmpty} from '.'

export class Item193436 {
  @IsOptional()
  @IsBoolean()
  'notifyFailed'?: boolean

  @IsOptional()
  @IsBoolean()
  'selected'?: boolean

  @IsOptional()
  @IsNumber()
  'stabilizationWindowSeconds'?: number
}

export class Item193435 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193436)
  'scaleDown'?: Item193436

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193436)
  'scaleUp'?: Item193436
}

export class Item193425 {
  @IsOptional()
  @IsString()
  'metrics'?: string

  @IsOptional()
  @IsNumber()
  'threshold'?: number
}

export class Item193424 {
  @IsOptional()
  @IsString()
  'endTime'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => ItemEmpty)
  'endWeekday'?: ItemEmpty

  @IsOptional()
  @ValidateNested()
  @Type(() => ItemEmpty)
  'repeatType'?: ItemEmpty

  @IsOptional()
  @IsString()
  'startTime'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => ItemEmpty)
  'startWeekday'?: ItemEmpty

  @IsOptional()
  @IsNumber()
  'targetCount'?: number
}

export class Item193415 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193425)
  'autoscalingRule'?: Item193425

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193424)
  'cronRule'?: Item193424

  @IsOptional()
  @IsString()
  'type'?: string
}

export class Item193413 {
  @IsOptional()
  @IsString()
  'az'?: string

  @IsOptional()
  @IsString()
  'sdu'?: string
}

export class Item193412 {
  @IsOptional()
  @IsString()
  'autoscalingLogic'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193435)
  'behavior'?: Item193435

  @IsOptional()
  @IsNumber()
  'maxReplicaCount'?: number

  @IsOptional()
  @IsNumber()
  'minReplicaCount'?: number

  @IsOptional()
  @IsString()
  'notifyChannel'?: string

  @IsOptional()
  @IsNumber()
  'status'?: number

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193415)
  @IsArray()
  'triggerRules'?: Item193415[]

  @IsOptional()
  @IsString()
  'updatedTime'?: string

  @IsOptional()
  @IsString()
  'updator'?: string
}

export class Item193410 {
  @IsOptional()
  @IsNumber()
  'id'?: number

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193413)
  'meta'?: Item193413

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193412)
  'spec'?: Item193412
}

export class GetEcpapiV2Sdus1SduNameHpasReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string
}
export class GetEcpapiV2Sdus1SduNameHpasResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193410)
  @IsArray()
  'items'?: Item193410[]

  @IsOptional()
  @IsNumber()
  'total'?: number
}
