/* md5: 8be25952a1c54b508bb9936ee4f4ad0e */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：ListClusterMeta
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8768
 */

import {IsOptional, IsNumber, IsString, ValidateNested, IsArray, IsBoolean} from 'class-validator'
import {Type} from 'class-transformer'

export class Item193036 {
  @IsOptional()
  @IsString()
  'azForDepconf'?: string

  @IsOptional()
  @IsString()
  'azV1'?: string

  @IsOptional()
  @IsString()
  'azV2'?: string

  @IsOptional()
  @IsString()
  'clusterType'?: string

  @IsOptional()
  @IsString()
  'createTs'?: string

  @IsOptional()
  @IsString()
  'descriptions'?: string

  @IsOptional()
  @IsString()
  'displayName'?: string

  @IsOptional()
  @IsString()
  'ecpVersion'?: string

  @IsOptional()
  @IsBoolean()
  'handleByGalio'?: boolean

  @IsOptional()
  @IsString()
  'karmadaKubeConfig'?: string

  @IsOptional()
  @IsString()
  'kubeApiserverType'?: string

  @IsOptional()
  @IsString()
  'kubeConfig'?: string

  @IsOptional()
  @IsString({each: true})
  @IsArray()
  'labels'?: string[]

  @IsOptional()
  @IsString()
  'monitoringUrl'?: string

  @IsOptional()
  @IsString()
  'platform'?: string

  @IsOptional()
  @IsString()
  'regionKey'?: string

  @IsOptional()
  @IsString()
  'segmentKey'?: string

  @IsOptional()
  @IsString()
  'uuid'?: string
}

export class GetEcpapiV2ClustermetasReqDto {
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  'pageNum'?: number

  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  'pageSize'?: number

  /**
    cluster_type,az_key,segment_key
  */
  @IsOptional()
  @IsString()
  'filterBy'?: string
}
export class GetEcpapiV2ClustermetasResDto {
  @IsOptional()
  @IsNumber()
  'total'?: number

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193036)
  @IsArray()
  'items'?: Item193036[]
}
