/* md5: 0c1647fd31f6a6630aa6038c6a658d57 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：GetDeploymentPreview
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=9606
 */

import {IsNotEmpty, IsString, IsOptional, ValidateNested} from 'class-validator'
import {Type} from 'class-transformer'

export class Item193313 {
  @IsOptional()
  @IsString()
  'az'?: string

  @IsOptional()
  @IsString()
  'tag'?: string

  @IsOptional()
  @IsString()
  'totalInstances'?: string
}

export class GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdDeployPreviewReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsString()
  'deployId': string

  @IsOptional()
  @IsString()
  'deploymentId'?: string
}
export class GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdDeployPreviewResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193313)
  'old'?: Item193313

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193313)
  'new'?: Item193313
}
