/* md5: 97b4c1462259277d707410f63f9cc8bb */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：ListClusterNodes
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8771
 */

import {IsNotEmpty, IsString, IsOptional, IsNumber, ValidateNested, IsArray} from 'class-validator'
import {Type} from 'class-transformer'

export class Item193170 {
  @IsOptional()
  @IsNumber()
  'allocatable'?: number

  @IsOptional()
  @IsNumber()
  'assigned'?: number

  @IsOptional()
  @IsNumber()
  'assignedUsage'?: number

  @IsOptional()
  @IsNumber()
  'capacity'?: number

  @IsOptional()
  @IsNumber()
  'free'?: number

  @IsOptional()
  @IsNumber()
  'reserved'?: number

  @IsOptional()
  @IsNumber()
  'used'?: number

  @IsOptional()
  @IsNumber()
  'usedUsage'?: number

  @IsOptional()
  @IsNumber()
  'workerAllocatable'?: number
}

export class Item193166 {
  @IsOptional()
  @IsString()
  'effect'?: string

  @IsOptional()
  @IsString()
  'key'?: string

  @IsOptional()
  @IsString()
  'value'?: string
}

export class Item193164 {
  @IsOptional()
  @IsNumber()
  'notReadyCount'?: number

  @IsOptional()
  @IsNumber()
  'readyCount'?: number

  @IsOptional()
  @IsNumber()
  'total'?: number

  @IsOptional()
  @IsNumber()
  'unknownCount'?: number
}

export class Item193163 {
  @IsOptional()
  @IsString()
  'key'?: string

  @IsOptional()
  @IsString()
  'value'?: string
}

export class Item193161 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193170)
  'cpu'?: Item193170

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193170)
  'disk'?: Item193170

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193170)
  'gpu'?: Item193170

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193170)
  'memory'?: Item193170
}

export class Item193159 {
  @IsOptional()
  @IsNumber()
  'capacity'?: number

  @IsOptional()
  @IsNumber()
  'count'?: number

  @IsOptional()
  @IsNumber()
  'unhealthyCount'?: number
}

export class Item193157 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193163)
  @IsArray()
  'labels'?: Item193163[]

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193161)
  'metrics'?: Item193161

  @IsOptional()
  @IsString()
  'name'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193159)
  'podSummary'?: Item193159

  @IsOptional()
  @IsString()
  'privateIp'?: string

  @IsOptional()
  @IsString({each: true})
  @IsArray()
  'roles'?: string[]

  @IsOptional()
  @IsString()
  'status'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193166)
  @IsArray()
  'taints'?: Item193166[]
}

export class GetEcpapiV2Clusters1UuidNodesReqDto {
  @IsNotEmpty()
  @IsString()
  'uuid': string

  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  'pageNum'?: number

  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  'pageSize'?: number

  /**
    support: status,role,label_key,label_value,
  */
  @IsOptional()
  @IsString()
  'filterBy'?: string

  /**
    support: todo
  */
  @IsOptional()
  @IsString()
  'orderBy'?: string

  @IsOptional()
  @IsString()
  'searchBy'?: string
}
export class GetEcpapiV2Clusters1UuidNodesResDto {
  @IsOptional()
  @IsNumber()
  'total'?: number

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193157)
  @IsArray()
  'nodes'?: Item193157[]

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193164)
  'summary'?: Item193164

  @IsOptional()
  @IsArray()
  'roles'?: any[]
}
