/* md5: 418bdf92a5746ded15d0b4046a180cc4 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：ListAzDetail
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1386&itf=8772
 */

import {IsOptional, IsString, ValidateNested, IsArray} from 'class-validator'
import {Type} from 'class-transformer'

export class Item193222 {
  @IsOptional()
  @IsString()
  'azKey'?: string

  @IsOptional()
  @IsString({each: true})
  @IsArray()
  'capability'?: string[]

  @IsOptional()
  @IsString({each: true})
  @IsArray()
  'clusters'?: string[]

  @IsOptional()
  @IsString()
  'env'?: string

  @IsOptional()
  @IsString()
  'name'?: string

  @IsOptional()
  @IsString()
  'version'?: string
}

export class GetEcpapiV2AzsReqDto {
  @IsOptional()
  @IsString()
  'env'?: string
}
export class GetEcpapiV2AzsResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193222)
  @IsArray()
  'items'?: Item193222[]
}
