/* md5: 518e437e55cb154c7a555edf96cecfe3 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：ListClusterDetail
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8767
 */

import {IsOptional, IsNumber, IsString, ValidateNested, IsArray, IsBoolean} from 'class-validator'
import {Type} from 'class-transformer'

export class Item192993 {
  @IsOptional()
  @IsNumber()
  'allocatable'?: number

  @IsOptional()
  @IsNumber()
  'assigned'?: number

  @IsOptional()
  @IsNumber()
  'assignedUsage'?: number

  @IsOptional()
  @IsNumber()
  'capacity'?: number

  @IsOptional()
  @IsNumber()
  'free'?: number

  @IsOptional()
  @IsNumber()
  'reserved'?: number

  @IsOptional()
  @IsNumber()
  'used'?: number

  @IsOptional()
  @IsNumber()
  'usedUsage'?: number

  @IsOptional()
  @IsNumber()
  'workerAllocatable'?: number
}

export class Item192969 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item192993)
  'cpu'?: Item192993

  @IsOptional()
  @ValidateNested()
  @Type(() => Item192993)
  'disk'?: Item192993

  @IsOptional()
  @ValidateNested()
  @Type(() => Item192993)
  'gpu'?: Item192993

  @IsOptional()
  @ValidateNested()
  @Type(() => Item192993)
  'memory'?: Item192993
}

export class Item192967 {
  @IsOptional()
  @IsString()
  'message'?: string

  @IsOptional()
  @IsString()
  'resourceName'?: string

  @IsOptional()
  @IsString()
  'title'?: string

  @IsOptional()
  @IsString()
  'type'?: string
}

export class Item192958 {
  @IsOptional()
  @IsNumber()
  'capacity'?: number

  @IsOptional()
  @IsNumber()
  'count'?: number

  @IsOptional()
  @IsNumber()
  'unhealthyCount'?: number
}

export class Item192957 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item192967)
  @IsArray()
  'alarms'?: Item192967[]

  @IsOptional()
  @IsString()
  'health'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item192969)
  'metrics'?: Item192969

  @IsOptional()
  @ValidateNested()
  @Type(() => Item192958)
  'nodeSummary'?: Item192958

  @IsOptional()
  @IsString()
  'observabilityLink'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item192958)
  'podSummary'?: Item192958

  @IsOptional()
  @IsString()
  'status'?: string
}

export class Item192956 {
  @IsOptional()
  @IsString()
  'azForDepconf'?: string

  @IsOptional()
  @IsString()
  'azV1'?: string

  @IsOptional()
  @IsString()
  'azV2'?: string

  @IsOptional()
  @IsString()
  'clusterType'?: string

  @IsOptional()
  @IsString()
  'createTs'?: string

  @IsOptional()
  @IsString()
  'descriptions'?: string

  @IsOptional()
  @IsString()
  'displayName'?: string

  @IsOptional()
  @IsString()
  'ecpVersion'?: string

  @IsOptional()
  @IsBoolean()
  'handleByGalio'?: boolean

  @IsOptional()
  @IsString()
  'karmadaKubeConfig'?: string

  @IsOptional()
  @IsString()
  'kubeApiserverType'?: string

  @IsOptional()
  @IsString()
  'kubeConfig'?: string

  @IsOptional()
  @IsString({each: true})
  @IsArray()
  'labels'?: string[]

  @IsOptional()
  @IsString()
  'monitoringUrl'?: string

  @IsOptional()
  @IsString()
  'platform'?: string

  @IsOptional()
  @IsString()
  'regionKey'?: string

  @IsOptional()
  @IsString()
  'segmentKey'?: string

  @IsOptional()
  @IsString()
  'uuid'?: string
}

export class Item192955 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item192956)
  'meta'?: Item192956

  @IsOptional()
  @ValidateNested()
  @Type(() => Item192957)
  'status'?: Item192957
}

export class GetEcpapiV2ClusterdetailsReqDto {
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  'pageNum'?: number

  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  'pageSize'?: number

  /**
    support: cluster_type,az_key,segment_key,status,health
  */
  @IsOptional()
  @IsString()
  'filterBy'?: string

  /**
    support: create_ts,node_count
  */
  @IsOptional()
  @IsString()
  'orderBy'?: string

  @IsOptional()
  @IsString()
  'searchBy'?: string
}
export class GetEcpapiV2ClusterdetailsResDto {
  @IsOptional()
  @IsNumber()
  'total'?: number

  @IsOptional()
  @ValidateNested()
  @Type(() => Item192955)
  @IsArray()
  'items'?: Item192955[]
}
