/* md5: bf9d2b7cae4e7c40a642e7b08c861472 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：HealthCheck
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1387&itf=8774
 */

import {IsOptional, IsString} from 'class-validator'

export class GetEcpapiV2CheckReqDto {}
export class GetEcpapiV2CheckResDto {
  @IsOptional()
  @IsString()
  'app'?: string

  @IsOptional()
  @IsString()
  'message'?: string
}
