/* md5: f77adac7746f8fc31f4e383b9464bc25 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：GetSDUSummary
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1392&itf=8798
 */

import {IsNotEmpty, IsString, ValidateNested, IsOptional, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class Item193537 {
  @IsOptional()
  @IsNumber()
  'canaryInstances'?: number

  @IsOptional()
  @IsNumber()
  'cpu'?: number

  @IsOptional()
  @IsNumber()
  'disk'?: number

  @IsOptional()
  @IsNumber()
  'healthyInstances'?: number

  @IsOptional()
  @IsNumber()
  'killingInstances'?: number

  @IsOptional()
  @IsNumber()
  'lastDeployed'?: number

  @IsOptional()
  @IsNumber()
  'mem'?: number

  @IsOptional()
  @IsNumber()
  'releaseInstances'?: number

  @IsOptional()
  @IsNumber()
  'runningInstances'?: number

  @IsOptional()
  @IsString()
  'sduName'?: string

  @IsOptional()
  @IsNumber()
  'stagingInstances'?: number

  @IsOptional()
  @IsNumber()
  'startingInstances'?: number

  @IsOptional()
  @IsString()
  'state'?: string

  @IsOptional()
  @IsNumber()
  'targetInstances'?: number

  @IsOptional()
  @IsNumber()
  'unhealthyInstances'?: number

  @IsOptional()
  @IsNumber()
  'unknownInstances'?: number
}

export class GetEcpapiV2Sdus1SduNameSummaryReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string
}
export class GetEcpapiV2Sdus1SduNameSummaryResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193537)
  'summary'?: Item193537
}
