/* md5: 10fcc7d6f7120731d8e3d35ada5daed8 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：GetDeploymentPreview
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8782
 */

import {IsNotEmpty, IsString, IsOptional, ValidateNested} from 'class-validator'
import {Type} from 'class-transformer'
import {ItemEmpty} from '.'

export class Item167997 {
  @IsOptional()
  @IsString()
  'az'?: string

  @IsOptional()
  @IsString()
  'tag'?: string

  @IsOptional()
  @IsString()
  'totalInstances'?: string
}

export class GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdDeploymentPreviewReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsString()
  'deployId': string

  @IsOptional()
  @IsString()
  'deploymentId'?: string
}
export class GetEcpapiV2Sdus1SduNameSvcdeploys1DeployIdDeploymentPreviewResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item167997)
  'old'?: Item167997

  @IsOptional()
  @ValidateNested()
  @Type(() => ItemEmpty)
  'new'?: ItemEmpty
}
