/* md5: ee243e69acc3ee8950c0b03f92dec84f */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：QueryECPEnumerations
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1389&itf=8791
 */

import {ValidateNested, IsArray, IsOptional, IsString} from 'class-validator'
import {Type} from 'class-transformer'

export class Item193406 {
  @IsOptional()
  @IsString({each: true})
  @IsArray()
  'enums'?: string[]

  @IsOptional()
  @IsString()
  'type'?: string
}

export class GetEcpapiV2EnumsReqDto {}
export class GetEcpapiV2EnumsResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193406)
  @IsArray()
  'allenums'?: Item193406[]
}
