/* md5: cf5af686f7a74f4c41063edc638d264a */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：ListAllSDUsSummary
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1392&itf=8800
 */

import {IsOptional, IsString, IsBoolean, ValidateNested, IsArray, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class Item193559 {
  @IsOptional()
  @IsNumber()
  'canaryInstances'?: number

  @IsOptional()
  @IsNumber()
  'cpu'?: number

  @IsOptional()
  @IsNumber()
  'disk'?: number

  @IsOptional()
  @IsNumber()
  'healthyInstances'?: number

  @IsOptional()
  @IsNumber()
  'killingInstances'?: number

  @IsOptional()
  @IsNumber()
  'lastDeployed'?: number

  @IsOptional()
  @IsNumber()
  'mem'?: number

  @IsOptional()
  @IsNumber()
  'releaseInstances'?: number

  @IsOptional()
  @IsNumber()
  'runningInstances'?: number

  @IsOptional()
  @IsString()
  'sduName'?: string

  @IsOptional()
  @IsNumber()
  'stagingInstances'?: number

  @IsOptional()
  @IsNumber()
  'startingInstances'?: number

  @IsOptional()
  @IsString()
  'state'?: string

  @IsOptional()
  @IsNumber()
  'targetInstances'?: number

  @IsOptional()
  @IsNumber()
  'unhealthyInstances'?: number

  @IsOptional()
  @IsNumber()
  'unknownInstances'?: number
}

export class GetEcpapiV2ServicesSdusSummaryReqDto {
  @IsOptional()
  @IsString()
  'sduName'?: string

  /**
    support filter by env、cid, Example: ?filter_by=env==test;cid==CN
  */
  @IsOptional()
  @IsString()
  'filterBy'?: string

  /**
    keyword to search, support sdu name
  */
  @IsOptional()
  @IsString()
  'keyword'?: string

  @IsOptional()
  @IsBoolean()
  'isGroup'?: boolean
}
export class GetEcpapiV2ServicesSdusSummaryResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193559)
  @IsArray()
  'items'?: Item193559[]

  @IsOptional()
  @IsNumber()
  'totalSize'?: number
}
