/* md5: a321c1873fef1541e19449ea20f6b829 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：QueryClusterDetail
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8770
 */

import {IsNotEmpty, IsString, IsOptional, IsBoolean, ValidateNested, IsNumber, IsArray} from 'class-validator'
import {Type} from 'class-transformer'

export class Item193110 {
  @IsOptional()
  @IsNumber()
  'allocatable'?: number

  @IsOptional()
  @IsNumber()
  'assigned'?: number

  @IsOptional()
  @IsNumber()
  'assignedUsage'?: number

  @IsOptional()
  @IsNumber()
  'capacity'?: number

  @IsOptional()
  @IsNumber()
  'free'?: number

  @IsOptional()
  @IsNumber()
  'reserved'?: number

  @IsOptional()
  @IsNumber()
  'used'?: number

  @IsOptional()
  @IsNumber()
  'usedUsage'?: number

  @IsOptional()
  @IsNumber()
  'workerAllocatable'?: number
}

export class Item193101 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193110)
  'cpu'?: Item193110

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193110)
  'disk'?: Item193110

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193110)
  'gpu'?: Item193110

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193110)
  'memory'?: Item193110
}

export class Item193096 {
  @IsOptional()
  @IsString()
  'message'?: string

  @IsOptional()
  @IsString()
  'resourceName'?: string

  @IsOptional()
  @IsString()
  'title'?: string

  @IsOptional()
  @IsString()
  'type'?: string
}

export class Item193093 {
  @IsOptional()
  @IsNumber()
  'capacity'?: number

  @IsOptional()
  @IsNumber()
  'count'?: number

  @IsOptional()
  @IsNumber()
  'unhealthyCount'?: number
}

export class Item193075 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193096)
  @IsArray()
  'alarms'?: Item193096[]

  @IsOptional()
  @IsString()
  'health'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193101)
  'metrics'?: Item193101

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193093)
  'nodeSummary'?: Item193093

  @IsOptional()
  @IsString()
  'observabilityLink'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193093)
  'podSummary'?: Item193093

  @IsOptional()
  @IsString()
  'status'?: string
}

export class Item193074 {
  @IsOptional()
  @IsString()
  'azForDepconf'?: string

  @IsOptional()
  @IsString()
  'azV1'?: string

  @IsOptional()
  @IsString()
  'azV2'?: string

  @IsOptional()
  @IsString()
  'clusterType'?: string

  @IsOptional()
  @IsString()
  'createTs'?: string

  @IsOptional()
  @IsString()
  'descriptions'?: string

  @IsOptional()
  @IsString()
  'displayName'?: string

  @IsOptional()
  @IsString()
  'ecpVersion'?: string

  @IsOptional()
  @IsBoolean()
  'handleByGalio'?: boolean

  @IsOptional()
  @IsString()
  'karmadaKubeConfig'?: string

  @IsOptional()
  @IsString()
  'kubeApiserverType'?: string

  @IsOptional()
  @IsString()
  'kubeConfig'?: string

  @IsOptional()
  @IsString({each: true})
  @IsArray()
  'labels'?: string[]

  @IsOptional()
  @IsString()
  'monitoringUrl'?: string

  @IsOptional()
  @IsString()
  'platform'?: string

  @IsOptional()
  @IsString()
  'regionKey'?: string

  @IsOptional()
  @IsString()
  'segmentKey'?: string

  @IsOptional()
  @IsString()
  'uuid'?: string
}

export class Item193073 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193074)
  'meta'?: Item193074

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193075)
  'status'?: Item193075
}

export class GetEcpapiV2Clusters1UuidDetailReqDto {
  @IsNotEmpty()
  @IsString()
  'uuid': string

  @IsOptional()
  @IsBoolean()
  'needStatus'?: boolean
}
export class GetEcpapiV2Clusters1UuidDetailResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193073)
  'detail'?: Item193073
}
