/* md5: 64ac2b207aeaac069aca2627535bdca7 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：ListSDUPods
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1391&itf=8793
 */

import {IsNotEmpty, IsString, IsOptional, ValidateNested, IsArray, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class Item193460 {
  @IsOptional()
  @IsString()
  'containerId'?: string

  @IsOptional()
  @IsString()
  'contianerName'?: string
}

export class Item193447 {
  @IsOptional()
  @IsString()
  'cid'?: string

  @IsOptional()
  @IsString()
  'clusterName'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193460)
  @IsArray()
  'containerInfo'?: Item193460[]

  @IsOptional()
  @IsNumber()
  'createdTime'?: number

  @IsOptional()
  @IsString()
  'env'?: string

  @IsOptional()
  @IsString()
  'idc'?: string

  @IsOptional()
  @IsNumber()
  'lastRestartTime'?: number

  @IsOptional()
  @IsString()
  'namespace'?: string

  @IsOptional()
  @IsString()
  'nodeIp'?: string

  @IsOptional()
  @IsString()
  'nodeName'?: string

  @IsOptional()
  @IsString()
  'phase'?: string

  @IsOptional()
  @IsString()
  'podIp'?: string

  @IsOptional()
  @IsString()
  'podName'?: string

  @IsOptional()
  @IsNumber()
  'podPort'?: number

  @IsOptional()
  @IsNumber()
  'restartCount'?: number

  @IsOptional()
  @IsString()
  'sdu'?: string

  @IsOptional()
  @IsString()
  'status'?: string

  @IsOptional()
  @IsString()
  'tag'?: string
}

export class GetEcpapiV2Sdus1SduNamePodsReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  /**
    support filter by env、cid, Example: ?filter_by=env==test;cid==CN
  */
  @IsOptional()
  @IsString()
  'filterBy'?: string
}
export class GetEcpapiV2Sdus1SduNamePodsResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193447)
  @IsArray()
  'items'?: Item193447[]

  @IsOptional()
  @IsNumber()
  'total'?: number
}
