/* md5: a4ed4508a5169de9ce8a02dd2b4139fa */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：ListWorkload
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8790
 */

import {IsOptional, IsString, ValidateNested, IsArray} from 'class-validator'
import {Type} from 'class-transformer'

export class Item193400 {
  @IsOptional()
  @IsString()
  'category'?: string

  @IsOptional()
  @IsString()
  'name'?: string

  @IsOptional()
  @IsString()
  'nameDisplay'?: string

  @IsOptional()
  @IsString()
  'type'?: string
}

export class Item193398 {
  @IsOptional()
  @IsString()
  'az'?: string

  @IsOptional()
  @IsString()
  'env'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193400)
  @IsArray()
  'workloads'?: Item193400[]
}

export class GetEcpapiV2WorkloadsReqDto {
  @IsOptional()
  @IsString()
  'env'?: string
}
export class GetEcpapiV2WorkloadsResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193398)
  @IsArray()
  'items'?: Item193398[]
}
