/* md5: b2ee95448f78d22884371cc4762b2273 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：AddClusterMeta
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8769
 */

import {IsOptional, IsString, IsBoolean, IsArray} from 'class-validator'

export class PostEcpapiV2ClustermetasReqDto {
  @IsOptional()
  @IsString()
  'uuid'?: string

  @IsOptional()
  @IsString()
  'displayName'?: string

  @IsOptional()
  @IsString()
  'kubeConfig'?: string

  @IsOptional()
  @IsString()
  'azV1'?: string

  @IsOptional()
  @IsString()
  'azV2'?: string

  @IsOptional()
  @IsString()
  'segmentKey'?: string

  @IsOptional()
  @IsString()
  'monitoringUrl'?: string

  /**
    If empty, default value equal to "native",
more enums seeing https://{ecp-openapi-domain}/ecpapi/v2/enums.
  */
  @IsOptional()
  @IsString()
  'kubeApiserverType'?: string

  /**
    ecpv1: only native capability,
leap: support bromo,
ecpv2: support bromo & native capability,
If empty, default value equal to "ecpv2",
more enums seeing https://{ecp-openapi-domain}/ecpapi/v2/enums.
  */
  @IsOptional()
  @IsString()
  'ecpVersion'?: string

  @IsOptional()
  @IsBoolean()
  'handleByGalio'?: boolean

  /**
    If empty, default value equal to "az",
more enums seeing https://{ecp-openapi-domain}/ecpapi/v2/enums.
  */
  @IsOptional()
  @IsString()
  'platform'?: string

  /**
    If empty, default value equal to "cis",
more enums seeing https://{ecp-openapi-domain}/ecpapi/v2/enums.
  */
  @IsOptional()
  @IsString()
  'clusterType'?: string

  @IsOptional()
  @IsString()
  'karmadaKubeConfig'?: string

  @IsOptional()
  @IsString({each: true})
  @IsArray()
  'labels'?: string[]

  @IsOptional()
  @IsString()
  'descriptions'?: string
}
export class PostEcpapiV2ClustermetasResDto {}
