/* md5: 9a9d8cd2d8e21d4b0bb390d888d57397 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：ScaleDeployment
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8787
 */

import {IsNotEmpty, IsString, IsOptional, IsNumber, IsBoolean} from 'class-validator'
import {Type} from 'class-transformer'

export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdScaleReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsString()
  'deployId': string

  @IsOptional()
  @IsNumber()
  'releaseReplicas'?: number

  @IsOptional()
  @IsNumber()
  'canaryReplicas'?: number

  @IsOptional()
  @IsBoolean()
  'canaryValid'?: boolean
}
export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdScaleResDto {}
