/* md5: c75608a164a227f581e5031f1d2227da */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：RestartDeployment
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8785
 */

import {IsNotEmpty, IsString, IsArray, IsOptional} from 'class-validator'

export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdRestartReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsString()
  'deployId': string

  @IsOptional()
  @IsString({each: true})
  @IsArray()
  'phases'?: string[]
}
export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdRestartResDto {}
