/* md5: 0df97d909ddd540b7f337a4c273a3b9b */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：GetPodsMetrics
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1391&itf=9607
 */

import {IsNotEmpty, IsString, ValidateNested, IsArray, IsOptional, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'

export class Item193525 {
  @IsOptional()
  @IsNumber()
  'applied'?: number

  @IsOptional()
  @IsNumber()
  'used'?: number
}

export class Item193522 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193525)
  'cpu'?: Item193525

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193525)
  'memory'?: Item193525

  @IsOptional()
  @IsString()
  'namespace'?: string

  @IsOptional()
  @IsString()
  'podName'?: string
}

export class Item193519 {
  @IsOptional()
  @IsString()
  'namespace'?: string

  @IsOptional()
  @IsString()
  'podName'?: string
}

export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPodsMetricsReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsString()
  'deployId': string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193519)
  @IsArray()
  'pods'?: Item193519[]
}
export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPodsMetricsResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item193522)
  @IsArray()
  'items'?: Item193522[]
}
