/* md5: 5b11474296bc3278e29850a7558f0eb3 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：GetPodsMetrics
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1391&itf=8797
 */

import {IsNotEmpty, IsString, ValidateNested, IsArray, IsOptional, IsNumber} from 'class-validator'
import {Type} from 'class-transformer'
import {ItemEmpty} from '.'

export class Item168094 {
  @IsOptional()
  @IsNumber()
  'applied'?: number

  @IsOptional()
  @IsNumber()
  'used'?: number
}

export class Item168090 {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item168094)
  'cpu'?: Item168094

  @IsOptional()
  @ValidateNested()
  @Type(() => ItemEmpty)
  'memory'?: ItemEmpty

  @IsOptional()
  @IsString()
  'namespace'?: string

  @IsOptional()
  @IsString()
  'podName'?: string
}

export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPodsMetricsReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsString()
  'deployId': string

  @IsNotEmpty()
  @IsString()
  'metrics': string
}
export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdPodsMetricsResDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => Item168090)
  @IsArray()
  'items'?: Item168090[]
}
