/* md5: a110dcc2cd104fb127100f19260c96fd */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：AddAppClusterConfig
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1385&itf=8765
 */

import {IsOptional, IsString} from 'class-validator'

export class PostEcpapiV2AppclusterconfigReqDto {
  @IsOptional()
  @IsString()
  'env'?: string

  @IsOptional()
  @IsString()
  'azKey'?: string

  @IsOptional()
  @IsString()
  'segmentKey'?: string

  @IsOptional()
  @IsString()
  'clusterUuid'?: string

  @IsOptional()
  @IsString()
  'scope'?: string

  @IsOptional()
  @IsString()
  'key'?: string

  @IsOptional()
  @IsString()
  'cmdbTenantId'?: string
}
export class PostEcpapiV2AppclusterconfigResDto {
  @IsOptional()
  @IsString()
  'id'?: string
}
