/* md5: 2f92aeb0ccde32a877f9a37e482e1b42 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：StopResourceBySdu
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1392&itf=8799
 */

import {IsNotEmpty, IsString} from 'class-validator'

export class PostEcpapiV2Sdus1SduNameSvcdeploysStopReqDto {
  @IsNotEmpty()
  @IsString()
  'stop': string

  @IsNotEmpty()
  @IsString()
  'sduName': string
}
export class PostEcpapiV2Sdus1SduNameSvcdeploysStopResDto {}
