/* md5: 2ffbbc2c4b13b9800926e7ec200e1e65 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：FullReleaseDeployment
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8784
 */

import {IsNotEmpty, IsString} from 'class-validator'

export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdFullreleaseReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsString()
  'deployId': string
}
export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdFullreleaseResDto {}
