/* md5: 3896a204ff23810b802385833a576646 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：DeploymentEditResource
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8783
 */

import {IsNotEmpty, IsString, IsOptional} from 'class-validator'

export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdEditresourceReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsString()
  'deployId': string

  @IsOptional()
  @IsString()
  'cpu'?: string

  @IsOptional()
  @IsString()
  'memory'?: string
}
export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdEditresourceResDto {}
