/* md5: 9eabd50c9ef62bd3c0d3eec25e9b4323 */
/* Rap repository id: 227 */
/* Rapper version: 2.1.14 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: https://rap.shopee.io/repository/editor?id=227
 */

/**
 * Interface name：RollbackDeployment
 * Rap url: https://rap.shopee.io/repository/editor?id=227&mod=1388&itf=8786
 */

import {IsNotEmpty, IsString, IsOptional, ValidateNested, IsArray} from 'class-validator'
import {Type} from 'class-transformer'

export class Item193382 {
  @IsOptional()
  @IsString()
  'image'?: string

  @IsOptional()
  @IsString()
  'name'?: string

  @IsOptional()
  @IsString()
  'phase'?: string

  @IsOptional()
  @IsString()
  'tag'?: string

  @IsOptional()
  @IsString()
  'timestamp'?: string
}

export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdRollbackReqDto {
  @IsNotEmpty()
  @IsString()
  'sduName': string

  @IsNotEmpty()
  @IsString()
  'deployId': string

  @IsOptional()
  @IsString()
  'deploymentId'?: string

  @IsOptional()
  @ValidateNested()
  @Type(() => Item193382)
  @IsArray()
  'containers'?: Item193382[]
}
export class PostEcpapiV2Sdus1SduNameSvcdeploys1DeployIdRollbackResDto {}
